
import React, { useState } from 'react';
import { format } from 'date-fns';
import { Collaborator } from '@/types/collaborator';
import { toast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Plus, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const CollaboratorFormHTML = () => {
  const [collaborators, setCollaborators] = useState<Collaborator[]>([]);

  const empresas = [
    'ALGAR TELECOM S.A.',
    'ALGAR TECH',
    'ALGAR SOLUCOES',
    'ALGAR AGRO',
    'ALGAR VENTURES',
    'UNA UNIVERSIDADE',
    'ALGAR MULTIMIDIA',
    'Grupo Orion',
    'SEM EMPRESA',
    'REGIA PNEUS',
    'SUPORTE INFORMATICA',
    'STERICICLE',
    'STARTEC',
    'P MAIS',
    'TOTVS',
    'Nova Empresa Engenharia',
    'cb',
    'labor suade',
    'metal frio',
    'geratec',
    'UPS SERVIÇOS',
    'automotion',
    'SO VEDAÇOES',
    'totus',
    'pcm consultoria',
    'solar',
    'interativa',
    'cernacom',
    'MOJOMIX',
    'tickt log',
    'M&M MANUTENÇÃO',
    'INSTITUTO NACIONAL DE SEGURIDADE SOCIAL',
    'amancio',
    'DNV',
    'CCIL',
    'ROSENDO TRANSPORTES',
    'eletrodata',
    'GD VIDROS',
    'VALFILM',
    'REGIA PENEUS',
    'TRANSMASO',
    'HEUFT',
    'VAZAO',
    'GERENCIAMENTO EM SEGURANÇA DO TRABALHO',
    'REAL PUBLICIDADE',
    'JG RECICLAGEM',
    'MD CERVES',
    'MEM',
    'LOW COST',
    'GC AUTOMAÇÃO',
    'QUANTICA BRASIL',
    '3 M',
    'NACIONAL TURBO DIESEL',
    'NACIONAL TURBO',
    'CENTRAL DOS ELETROS',
    'ECOLAB',
    'ATRIVIDA',
    'AGAPE',
    'TESLA',
    'VICTOR DIESEL',
    'LDB',
    'SÃO JOSÉ',
    'COLETIVO JOVEM',
    'STERICYCLE',
    'HCL',
    'SGP',
    'BGM',
    'NWN TRANSPORTE',
    'MWM TRANSPORTE',
    'MAVIL',
    'ASA BRANCA',
    'PANIFICADORA VASCONCELOS',
    'FMAGALHAES',
    'SUPERGASBRAS',
    'INTERSAFETY',
    'PRESTEX',
    'FRS',
    'GESTOR',
    'REBOQUE SAO JOSE',
    'CABO BRANCO',
    'GILOG',
    'FG CAVALCANTE',
    'DEKRA',
    'ATREVIDA',
    'NSG',
    'PROBETON',
    'METALUGICA',
    'G ORENGO',
    'COMBATE',
    'VIPAL',
    'CAGEPA CAMPANHA',
    'ELETROTRAFO',
    'REAL',
    'SAMARTIN',
    'PNEUS',
    'APVIDA',
    'ELETROCELO',
    'TRANS,DE VALORES',
    'SADA',
    'ANTON PAAR',
    'MECANEVES',
    'LOG FRIOS',
    'TRANSPORTES',
    'BRAZUL',
    'DOS MACACOS',
    'FPB',
    'NACIONAL',
    'TRANS.',
    'TAMIJU',
    'FLOUIR',
    'TRANSPORTE',
    'HAPVIDA',
    'GR S/A',
    'NIGRO',
    'CIVIL',
    'MATHEUS FEST',
    'CAMABRA',
    'SEMPRE QUIMICA',
    'SAO JOSE',
    'MOS',
    'BOREAL',
    'LOCAMERICA',
    'MERCURIO',
    'PROGRESSO',
    'ENGENHARIA',
    'NORDIFE',
    'NACIONALGÁS',
    'DIEBOLD',
    'ECE',
    'WALSERV',
    'agra',
    'ONLINE',
    'JLTC',
    'KAIZEN',
    'MASTER BOI',
    'ALVORADA',
    'EXPRESSO GONÇALVES',
    'LEÃO',
    'TETRA PAK',
    'SERVISOS',
    'MP',
    'khs',
    'SM TRANSPORTE',
    'COREMAL',
    'BRG',
    'ministerio do trabalho',
    'COOP',
    'CENTRO AR',
    'ESTAF EQUIPAMENTOS',
    'ENERGISA',
    'PROTEMAXI SEGURANÇA',
    'BOM',
    'hexis',
    'emerson luiz dos santos',
    'UPTON',
    'BALL',
    'VG TECH',
    'NORSA CABO DE SANTO AGOSTINHO',
    'SUPERGABRAS',
    'merck',
    'protec',
    'selva',
    'ABB',
    'CORREIA E PEIXOTO',
    'tetra pak1',
    'UNIVERSAL',
    'coopergas',
    'CONTRUMAIS',
    'HNR',
    'QUALINTER',
    'uptonerfg',
    'pcmwdfe',
    'ELETROTAFO',
    'itep',
    'ASSUNÇÃO',
    'TAYTAMIJU',
    'HEINEKEN',
    'MANGABEIRA',
    'MATERIAIS',
    'TRANSPRTE',
    'TERMO BEM',
    'TETRA PACK',
    'TECNOLOGIA',
    'SOLAR CAF',
    'CRISTAL PET',
    'khsk',
    'PB AMBIENTAL',
    'METAL PRATICO',
    'MAQ ENGENHARIA',
    'FONTANELA',
    'CSI',
    'KM',
    'LOCAR',
    'TRICS LOG',
    'LIQUIDE',
    'RCW',
    'samatec',
    'lgv',
    'KEIJO',
    'CENTRAL ORTE FRUTAS',
    'cms',
    'BAUKO',
    'GRAFICA JB',
    'TERMACO',
    'domino',
    'IBS',
    'SINDCATO',
    'ADS',
    'JS TRUCK',
    'COMPET',
    'SUPER BID LEILOES',
    'VIDIOJET',
    'MIRVI',
    'PRISMATUR',
    'WHITE MARTINS',
    'DEEC OTICA',
    'ATLAS',
    'CELIO TRANSPORTE',
    'CELPE',
    'ASTECENDIO',
    'PROXXI',
    'PRESTETEC',
    'EXATA CARGO',
    'GE WATER',
    'ANJ',
    'ICETOS',
    'protege-sms',
    'SOLAR ESCRITÓRIO CENTRAL',
    'KARNE E KEIJO',
    'MC PACK',
    'velog',
    'ELOS',
    'TECLABOR',
    'MOTIVAR',
    'CHN',
    'SPIRAX SARCO',
    'NOVA ERA TRANSPORTE',
    'NOVA ERA TRANSPORTES',
    'PRESS',
    'ALPINISMO',
    'PROTELE ENGENHARIA',
    'PROTEGE',
    'INDUSTRIA REUNIDAS RENDA S.A',
    'ENGENHAR',
    'servis',
    'BRF S.A',
    'SENAI PERNAMBUCO',
    'VALMASTER',
    'antopar',
    'RMS INDUSTRIALTECNICA',
    'BRASIL GAS',
    'FLUE',
    'GUINCHOS',
    'SMART  CONSULTORIA',
    'NOVAL',
    'BIO AGRE',
    'BMS',
    'JR',
    'bens',
    'BETON',
    'DOM',
    'cagece',
    'correrecnica',
    'TEKNOL',
    'GASBRASS',
    'FESTE',
    'LIDER TELECOM',
    'souza e marcedo',
    'P.CIVIL',
    'LINCON',
    'MACRO',
    'MR BOMBAS E MOTORES',
    'PETROBRAS',
    'FERMAC',
    'microtec',
    'sc correntes',
    'PROX',
    'SEGURANÇA',
    'tranportes',
    'PROTECTA',
    'gocil seguranca',
    'SOLARIS',
    'corremaq',
    'FIMAP',
    'montcal',
    'orcan',
    'CONSTUMAS',
    'RODOBENS',
    'rgis',
    'VERTICAL',
    'CETIS',
    'TRANS',
    'PERFIL',
    'ifl',
    'TARZAN',
    'BONFIM',
    'MONTEC',
    'RECUPERADORA',
    'ROULD',
    'BICH BLINTS',
    'pm',
    'Cross Santa Cruz',
    'NS Brazil Revestimentos Especiais',
    'LIESS',
    'GENESIS',
    'MC REPRESENTAÇÕES',
    'RM',
    'BATISTI',
    'CASA DA MOEDA DO BRASIL',
    'EWE CONSULTORIA E INSPEÇÃO',
    'vip encomendas',
    'gerentec',
    'VASF',
    'REDE CONECTA',
    'GRANBEL',
    'KAEL DISTRIBUIDORA',
    'AROL',
    'BRF',
    'RODOBANC',
    'policia',
    'METALFRIO',
    'WORK TECH',
    'BELT',
    'TRIXLOG',
    'BEX',
    'LINQ',
    'STARTUP',
    'NETZSCH',
    'MULTIPLOS',
    'sipa',
    'E2PS',
    'UNIS',
    'PK',
    'PINTEMAR',
    'ALFA',
    'CISVIVER',
    'hd transportes',
    'IBL',
    'BOA VIAGEM',
    'ETECH COMPRESSORES',
    'MS',
    'AL',
    'BRADESCO',
    'CONVERGE',
    'AK',
    'LF',
    'LOG FRIO',
    'RGL',
    'USIMAR',
    'DOTO',
    'MADIS',
    'SEW',
    'SCHAFER',
    'L AMORIM',
    'DALL AGNOL',
    'ARTES',
    'LAMORIM',
    'FAZ PROMO',
    'TOPRINT',
    'CEFOR',
    'A',
    'RB',
    'GILSON MEDEIROS',
    'USIANA OLHO DAGUA',
    'COMAPRO',
    'RENOL SERVICE',
    'AGOGOL',
    'GOLGOL',
    'MAC ENGENHARIA',
    'RAWTEC',
    'FRIO',
    'VICTORDISEL',
    'AVANTE',
    'HIDROSONDA',
    'PS TRANSPORTE',
    'ECORPLAST',
    'CARBO GAS',
    'CIANO SOLUÇOES AMBIENTAIS',
    'VAL',
    'valfilme',
    'IMAGEN',
    'NACIONAL GÁS',
    'TECHNOFRIO',
    'SEGURADORA',
    'MNS METALURGICA',
    'SPRI',
    'LUMINS',
    'sl solar',
    'PAU BRASIL',
    'RIO DO PEIXE',
    'VVC',
    'RAPIDÃO BR',
    'TRANSBONO',
    'IBNOX',
    'PERICIA',
    'FIEMA',
    'PROTECMA',
    'ANTONIO MOTOS',
    'TOLEDO',
    'DMARI',
    'PPQ',
    'NOE LOGISTICA',
    'bom pão',
    'arame',
    'cvm',
    'GDM',
    'COBESA',
    'BATIST',
    'SÓ MOTORES',
    'gs mangueiras',
    'PATIO NORTE',
    'MENTAL MONTE',
    'GALVAO',
    'JAD EXPRESS',
    'TERA TELECOM',
    'GBLEX',
    'LINEAR',
    'nos controle',
    'LUARTE',
    'MAC FACILITEIS',
    'galpão de ideiaa',
    'BUFFET BOM DEMAIS',
    'amc do brasil',
    'SERCOS',
    'SIK',
    'FERGE',
    'Empresa testeF',
    'JA',
    'MADSERVES',
    'CALDADO TRANSPORTE',
    'JC DECALTES',
    'DOUTOR BATERIA',
    'bombeiro',
    'radiotech',
    'MENDES PINTO',
    'AHT',
    'CHIAVERINI',
    'universal transporte',
    'grande trabalho sim',
    'PNEU CENTER',
    'revitaliza eng',
    'strada',
    'prodeg auditoria',
    'PB GAS',
    'D LASER',
    'HAVAINA',
    'TQS',
    'RUENSE',
    'sidicato',
    'BOSCH',
    'IMPERIO SERANO',
    'COZITEC',
    'faisca soluções',
    'T',
    'TAO',
    'SEMEQ',
    'installer',
    'DISTRIBUIDORA MEDEIROS',
    'MADISA',
    'QUALITY',
    'AEGIS',
    'RA SOLUÇÕES INDUSTRIAIS',
    'SANTO AGOSTINHO',
    'MOVELOG',
    'comptec',
    'JT',
    'BELA FESTA',
    'Despoluir',
    'york',
    'CERRADO',
    'JS DA PENHA',
    'CMV DO MEARIM',
    'EMPRESA1',
    'ALUGUE',
    'alupe',
    'teste visão',
    'alupe teste',
    'FARADAY',
    'logistica',
    'SOMOV',
    'GIL MOTO',
    'ATC',
    'TRANSBRAGA',
    'ICP',
    'THT',
    'PB',
    'sm adesivagem',
    'FGENES',
    'perto',
    'super gas',
    'PISOS',
    'TECLOBAR',
    'HYTORC',
    'LCB',
    'LATAN',
    'ALFEX',
    'OFIMEC',
    'LL-ENGENHARIA',
    'ambito',
    'JA METALURGICA',
    'CONCRETOS',
    'PROJECTA',
    'heiniken',
    'PMAIS',
    'GTECK',
    'OLIVEIRA',
    'aço brasil',
    'WR TRANSPORTE',
    'REBOQUE',
    'FAM',
    'OI',
    'grupo sucesso',
    'VIEW',
    'FLUENCE',
    'exactcontrou',
    'LOGFRIO',
    'C.V DO MEARIM',
    'hap vida',
    'TEC TUBE',
    'R LUZ',
    'positronic',
    'SA CAVALCANTE',
    'ferreira serviço',
    'METALMA',
    'SADA TRANSPORTE',
    'PRODELOG',
    'METRO',
    'phocus',
    'I NOVA',
    'service',
    'COPA EXITO',
    'EMVIPOL',
    'HG',
    'TECNOMAN',
    'VIGILANCIA SANITARIA',
    'CROWN',
    'unidas',
    'montagem',
    'SESI',
    'samed',
    'REFPALET',
    'dds',
    'instituto maranhense',
    'somas',
    'LIMPA FOSSA PARNAMIRIM',
    'JORNAL AGORA',
    'CHAVEIRO',
    'uranus',
    'AUTODRO',
    'AUT SERVIÇE',
    'TECALTO',
    'VEPREL',
    'trt',
    'URBE PROJETOS E CONSTRUÇÕES',
    'ARY GUINCHO',
    'DATA PROMO',
    'MAC FACILIS',
    'DE DAVI',
    'OJB TRAGOGRAFO',
    'PONTO DIGITAL',
    'flex',
    'DATA PROM',
    'TECNOMAM',
    'CLAND',
    '2.G',
    'PB AVERLINO',
    'VALSERV',
    'SOLUÇOES',
    'PRODEG',
    'MJS TRANSPORTES',
    'MJS',
    'MARTINS',
    'CHAMATEX',
    'RAPIDOBR',
    'DIVERSAY',
    'sadia',
    'tres corações',
    'maquinox',
    'CAVALCANTE ARQUITETURA',
    'multifrutas',
    'jma',
    'CAMPINENSE',
    'vipetro',
    'CEPA',
    'MILLS',
    'SÁ CAVALCANTE',
    'gold shopping',
    'TRANSNET',
    'seleção',
    'candidato',
    'agroquimica',
    'UNIGRAF',
    'compal',
    'fenix',
    'supergas',
    'distribuidor de peças',
    'krones',
    'Qualinte',
    'BRASEV',
    'canpack',
    'casa do menor trabalhador',
    'BRASECO',
    'NC  TRANSPORTE',
    'TECNOFRIL',
    'SSO RESGATE',
    'forbb',
    'video jet',
    'PLANUS INF',
    'DXD ENGEN',
    'MObil',
    'ASTRAL',
    'SUPER GÁS BRAS',
    'MIDIA DIGITAL',
    'KJP',
    'protemaxi',
    'SUBSOIL',
    'TCM EXPRESS',
    'LARIFO',
    'mosaico',
    'A e B MUDANÇAS',
    'GS CAVALCANTE',
    'FeJ POÇOS',
    'dararu vidros',
    'FLUIR',
    'CAEL',
    'MSLOG',
    'LEAL VASCONCELOS',
    'SUS',
    'MOTO LINK',
    'STOMPO',
    'ELOG',
    'LC CLIMATIZAÇÃO',
    'algas',
    'PAULO MELO',
    'moloke',
    'POTENCIAL ENGENHARIA',
    'ENTREVISTA',
    'unimetais',
    'TEC-HIDRO',
    'OTORTEC',
    'wso',
    'conceito',
    'ARPLAN',
    'CLIMATEC',
    'DUBICO',
    'TOPLINE',
    'MONTE FORTE',
    'SINE-PI',
    'RAVI',
    'CRIL',
    'MS LOG',
    'CONS',
    'TOP MANUTENÇÃO',
    'QMC',
    'cons. amacio',
    'EMPACK',
    'leite cem',
    'MAKE',
    'AMACIO',
    'SMS',
    'BIOAGRI',
    'LOWCOSP',
    'ciee',
    'MAREL',
    'NA ENTULHO',
    'visar transportes',
    'FEDEX',
    'PLANOS',
    'MAYKAWA',
    'MATEUS',
    'GRSA',
    'tigro',
    'AZUL CARGO',
    'SERGIO MATERIAL DE CONSTRUÇÃO',
    'macropack',
    'RR REFRI',
    'BELAS FESTAS',
    'Eespaço Virtual',
    'INOVER',
    'ades',
    'inmetro',
    'mestre sala',
    'RB TRANSPORTES',
    'AGUAS DE TERESINA',
    'X TEC',
    'EBENEZER',
    'ALTO MOLAS PROGUESSO',
    'HSE',
    'GLOBAL CARGO',
    'SAMAR',
    'ASSIS',
    'RANDON',
    'destaque reveste',
    'doce quitanda',
    'FESTO',
    'AVEX',
    'NORDEX LOG',
    'MAC-Q',
    'BR REBOQUE',
    'LIMA CANDEIA',
    'TELAPORTE',
    'DENVER',
    'MEW. BRASIL',
    'IOSTAQUIO',
    'ENGESERVE',
    'JUNIOR DECLARAÇÕES',
    'AEROPORTO ALUIZIO A.',
    'THIAGO FESTA',
    'PROBRETON',
    'ecotec',
    'LAUDEX',
    'ENLUR',
    'RESGATE',
    'FENIX MOVEIS',
    'MD',
    'UNISYS',
    'pb-ambiental',
    'A GERADORA',
    'ARCKMIRANDA',
    'rodoviario nordestino',
    'TRISLOG',
    'MV CONSTRUTORA',
    'CASA E COR',
    'MOTO EXPRESS',
    'BECKMAN',
    'ANALDO REBOQUES',
    'FOURFLEX',
    'NSI',
    'ORTOTEC',
    'KOMATEC',
    'consultoria',
    'MONSTER',
    'BRASIL GÁS',
    'VAL MÓVEIS',
    'MATINCETIS',
    'PARKMATIC',
    'New empresa',
    'nova empresa',
    'empresa teste 01',
    'ESFERA',
    'LÍDER TELECON',
    'FAVELA DO SAMBA',
    'TRANSPANTANAL',
    'LL ENGENHARIA',
    'ANTONIO OVO',
    'coca-cola brasil',
    'agogo',
    'FESTA DE BALAO',
    'ageradora',
    'BRASPRES',
    'KURIOS',
    'C3 ENGENHARIA',
    'TOPPER',
    'rtr',
    'auxTeste',
    'BRASUL',
    'COMATEC',
    'Clinepipe',
    'HC',
    'EMBRATEL',
    'QUALITAL',
    'ARAUJO ABREU',
    'EXPRESS TCM',
    'khs Indústria de Máquinas LTDA',
    'sonata',
    'LIMA TRANSPORTE',
    'REBOQUE SÃO JOSÉ',
    'Metal truck',
    'Tolledo',
    'RS TRANSPORTES',
    'ANTÔNIO OVOS',
    'md teste',
    'PURELENS',
    'NBS',
    'JAEL MAQ',
    'nasa',
    'DANFUSS',
    'Petrobrás',
    'VOTORANTIM',
    'VISAR',
    'tay tamiju',
    'TELEMACK',
    'MARAJÁ',
    'casa do construtor',
    'restec',
    'MAXSLG',
    'jato vidro',
    'ABC INCÊNDIO',
    'AD GASES',
    'UNIÃO PAULISTA',
    'GBEX',
    'SETE ENGENHARIA',
    'COMPANHIA PB DE TEATRO',
    'DWA ENGENHARIA',
    'DTW ENGENHARIA',
    'USITEC',
    'LOCKCENTER',
    'BR LOGISTICA',
    'TECLABO',
    'Polypack',
    'LIMNOS',
    'OLIVEIRA LOGISTICA',
    'COMPETEC',
    'CREA MA',
    'TOC RETOQUE TINTAS',
    'GARANTIA REAL',
    'ccl',
    'GRUPO SIMÕES',
    'AIR SEMEAR',
    'ROBERTO TRINDADE GRAVAÇÕES',
    'BUS TRANSPORTES',
    'FISIOQUALI',
    'RCR',
    'MAPE TRANSPORTES',
    'TRANBRAGA',
    'TITARA',
    'GTP',
    'CONSELHO DE ENERGIA NUCLEAR',
    'MONTETUDO',
    'RAPIDÃO COMETA',
    'TECSUL',
    'POSITIVA SERV. INDUST',
    'LRC COMERCIO LTDA',
    'PUBLICO FEDERAL',
    'EMAPLA',
    'almeida junior',
    'METALURGICA',
    'gps',
    'CARNES',
    'FUCHS',
    'SD engenharia',
    'ALIMENTOS',
    'RECIFER',
    'MARELLI',
    'GEANE GALVAO',
    'DESIGNER BRASIL',
    'ESCAPE HOUSE',
    'DUDU MATERIAL',
    'SaS turbo',
    'dsr',
    'abcdert',
    'FACULDADE PITAGORAS',
    'TRAMONTINA',
    'PLURAL',
    'PACK',
    'UNP',
    'PROARDI',
    'BEM AMIGO',
    'RANDSTAD',
    'Natal Telecom',
    'GBTecnica',
    'INTERTEC',
    'DIR PRODUCAO',
    'MARY KEY',
    'LOJA DAS CORRENTES',
    'MC TRANSPORTES',
    'ar',
    'IDEMA',
    'AMBIENTAL',
    'CONTROLE TECNICO',
    'VASCONCELOS EVENTOS',
    'aguiar eng',
    'MOURA',
    'MCN TELECON',
    'HANDSTARD',
    'PALETRANS',
    'TRANS. EPOCA',
    'MOOVE ENERGIA',
    'EZICOM',
    'SENASTEC',
    'GRANITUS',
    'CONSTRUÇÕES',
    'INST. FLORENCE',
    'OdontoPrimus',
    'EMBERA',
    'CHRONUS',
    'MANJA',
    'RODO CARGAS',
    'ERNEST',
    'MEDEIROS',
    'MC Motos',
    'BRINQUEDOS E BRINCADEIRAS',
    'ECOLABE',
    'Engenharia e Serviços',
    'BACABAL REFRIGERACAO',
    'Manutenção e consultoria',
    'Metal Mecanica',
    'Automação',
    'EXCELLENCE',
    'PLASTICOS NOVEL',
    'projetos',
    'POLIPACK',
    'MANUTENÇÃO',
    'PESAGEM',
    'BIOTECS ENGENHARIA',
    'VIDRAÇARIA',
    'G A GUINDASTE',
    'Embalagens',
    'Auditor',
    'solucoes ambientais',
    'Nutri',
    'QUIMITEC',
    'COLETA',
    'Equipamentos',
    'ZAPE',
    'LOCDECORE',
    'informatica',
    'IMPRESSORAS E CIA',
    'SCOLLT',
    'RN JUNIOR',
    'LOGUINTE',
    'Bombas',
    'FLOREST',
    'MPN',
    'LOPESTEC',
    'DIVERGENTE',
    'ELINQ',
    'JOBTECH',
    'g trigueiro',
    'ROLIMEC',
    'Fonte da Vida',
    'CENARCOM',
    'VENTARE',
    'VIDRAÇARIA ALUMINIO E CIA',
    '1 LUZ EVENTOS',
    'ZCOM',
    'GRAFICA',
    'Peças',
    'comaf',
    'FMAGALHÃES',
    'REDUX',
    'MUNDO DO VIDRO',
    'ART',
    'NS BRASIL',
    'CT GAS',
    'proteção visual',
    'FOCA CARGA',
    'PROCESS',
    'FILTEC',
    'MIAKI',
    'Artigos para Laboratórios',
    'ELETROCLIMA',
    'RCM ENGENHARIA',
    'hp',
    'CARNEIRO',
    'DELL',
    'SIPA',
    'ENTULHO POTIGUAR',
    'CAERN',
    'EXTINTORES',
    'REFRIGERAÇÃO',
    'LOPES TEK',
    'Tecnoiso',
    'ES MONTAGEM',
    'BMD',
    'comtrasil',
    'SOFERRO',
    'MAPROS',
    'JUNGHEINRICH',
    'BLOCO',
    'SINDBEB',
    'SERVSEC',
    'KUKA ROBOTER',
    'Mirante',
    'SHERWILLAMS',
    'tecno',
    'conserv',
    'LK LOGISTICA',
    'DEVICE',
    'AIS INSPEÇÃO',
    'BGM ALIMENTOS',
    'SANMARTIN',
    'SÃO JOÃO',
    'BM SONDAS',
    'SERVI CONSULTORIA',
    'PRONTOSERV',
    'SEG',
    'BURGMANN',
    'tec',
    'segvieg',
    'AILERT',
    'AIR LAB',
    'sindi',
    'BR',
    'DACAR',
    'radio',
    'DUAL TEC',
    'TRANSFORTECH',
    'REOPEM',
    'Danfoss',
    'CRISTAL ENGENHARIA',
    'ORDEM DOS ADVOGADOS DO BRASIL',
    'Filho',
    'GELA NORDESTE',
    'PRINT',
    '\\nGe',
    'Esmaltec',
    'PORTO SEGURO',
    'grupo brasmo',
    'Interativa Empreendimentos e Servicos de Limpeza e Construcoes LTDA',
    'GRANDE',
    'trix',
    'open',
    'PONTUAL SERVIÇOS',
    'Forbo',
    'AGRUPAR',
    'NORDESTE',
    'de vida',
    'FUNCIONAL',
    'PAKMATIC',
    'Federal',
    'OMNITRADE',
    'CONSELHO REGIONAL DE QUIMICA',
    'GHS',
    'SSMA',
    'lipesa',
    'nox',
    'técnica',
    'M DIAS BRANCO',
    'ANDESUS',
    'EFICIENTE',
    'Lubrisirt',
    'clinica ceda',
    'WMS',
    'PALL',
    'eketro',
    'sigma',
    'COMERCIOS E SEVIÇOS',
    'JAMEF - TRANSPORTES',
    'CUTELARIA BR',
    'HENKEL',
    'TRUCK',
    'COMERCIO DE MAQUINAS',
    'IDEIAS',
    'Correios',
    'Crion',
    'DUAL',
    'PXX',
    'PROSEGUR',
    'PKG Brasil',
    'MIX',
    'SANTANA',
    'refrisul',
    'WINSPECT',
    'empredimemntos',
    'Gale',
    'ENERGY',
    'CONSELHO FEDERAL DE QUÍMICA',
    'DIAS',
    'ZELA',
    'JR ARAUJO',
    'GF',
    'KYU',
    'Epo Montagem',
    'INDUST. CIMENTO',
    'CARNE QEIJO',
    'PAO DOCE MEL',
    'ASSECH',
    'AGUA VIDDA',
    'SEGIVEW',
    'LEGUMES E CIA',
    'Kay',
    'motores',
    'manutec',
    'ASSECORIA E TREINAMENTO',
    '_',
    'Santos',
    'Promo',
    'FM MOTOS',
    'SOLITICAS',
    'SOLISTICA',
    'OVOS',
    'VACCINE',
    'Brasil',
    'BUREAU',
    'visita',
    'ART FRUTAS',
    'industria e comercio ssa',
    'trasnportes',
    'autentica',
    'MERCEDES',
    'FESTAS',
    'GÁS BRAS',
    'MATEC INFOR',
    'VASCONCELOS',
    'PRESERV',
    'EQUIPAR',
    'segseguro',
    'Constutura',
    'vida',
    'CMC',
    'visitante',
    'MASTERBOI',
    'unilare',
    'desart',
    '5A',
    'PREVENÇÃO',
    'tech',
    'Boticario',
    'sousa log',
    'LEGUMES & CIA',
    'LOG',
    'MYNASRKI',
    'MOSAIC',
    'fs logistica',
    'TRANS VICTOR',
    'TRANSGESP',
    'SEMEAR',
    'PEIXOTO',
    'one wey',
    'COSTA ENGENHARIA',
    'ARCAM',
    'EMPLACAMENTO',
    'GB BEX',
    'CLINICAS DAS CADEIRAS',
    'JOCARTS',
    'SÓMANGUEIRAS',
    'transportadora',
    'geoser serviços geológicos',
    'PB GÁS',
    'MELHORAMENTOS',
    'JOHNSON CONTROLS',
    'OMRON',
    'VALMETAL',
    'SMC',
    'FM2C',
    'siemens',
    'VMC TRANSPORTES',
    'CRN',
    'DECRA',
    'servimateltda',
    'MEGA NORDESTE',
    'OPÇÃO',
    'ALPUNTO',
    'watts led',
    'Guarnieri Engenharia',
    'MTECH',
    'SARCO',
    'RECIFE COMERCIO',
    'sindicato',
    'DELTA CONTAINERS',
    'karnekeijo',
    'endress+houser',
    'TN TRANPORTE',
    'ALBERSON B FOTOGRAFIA',
    'fribal',
    'PANIFICADORA VASCOLCELOS',
    'MAGNABEL',
    'REVIBRAS',
    'ATEC MANUNTEÇÃO EMP.',
    'PAVEL',
    'edj poda',
    'MARQSERVICE',
    'AEROLIM',
    'NORDESTE MANUTENÇÃO',
    'MOB TELECON',
    'TCNO FRIO',
    'FORTAL AUTOMAÇÃO',
    'EMERSON',
    'BOM LEITE',
    'EMGEARRIA CORREA PEXOTO',
    'PBGAS',
    'LOCAÇÕES',
    'SINALIZE',
    'SHERATON',
    'gsm gráfica',
    'EMITTER',
    'brasilgas',
    'LOOP BRASIL',
    'AUTO',
    'QUIMICOS',
    'MAR SERVICE',
    'CORRENTES',
    'HORAND',
    'Previne',
    'NORTE',
    'VIA LINPA',
    'FAZMAN',
    'EMPLACADORA',
    'mc enventos',
    'TERMICA',
    'exbras engenharia de insendio',
    'SELEÇAO MUNDO SERVIÇOS',
    'G1000',
    'RE',
    'SEMPRE QUÍMICA',
    'VECHEL',
    'Life',
    'GEISEL',
    'JPINTO',
    'BRS',
    'AUDITORIA',
    'ROOTER',
    'ISMA',
    'DELMAR',
    'CALIBRAÇÕES',
    'TECMAR',
    'INJETROTEC',
    'comunicação visual',
    'FORTE',
    'ROLTEX',
    'NORTE SOLUCO',
    'ANDRADE',
    'CIMCORP',
    'PERTO CATRACA',
    'LIRA',
    'Sistemac',
    'PREDMEC',
    'OTTIMA',
    'CHAPOS',
    'INTERATIVA EMPREENDIMENTOS',
    'thay festas',
    'BIFE NEO ANTUNES',
    'unibra faculdade',
    'MOTOSHOCK',
    'perteci',
    'NKA',
    'ANDALUZ',
    'TRIX  log',
    'BDG',
    'CARGO',
    'CAPACITAR',
    'REAL SEGURAÇA',
    'KAPO',
    'transvicon',
    'MOLDINTEC',
    'focus',
    'CHUVA DE IDEIA',
    'POTIGÁS',
    'COLLTHECH',
    'ENG',
    'exis',
    'BANDEIRANTES',
    'idustrial',
    'MIX SERVIÇOS',
    'Integração',
    'LOGMAN',
    'FARRAPOS',
    'MONTAN',
    'gren maia',
    'log log',
    'KLINGER',
    'ENCEETEL',
    'ONE',
    'DREAM',
    'cap',
    'Policlinica',
    'FLUIDCOM',
    'PIZANI',
    'ALEX REBOQUE',
    'EDS ENGENHARIA',
    'planus informatica',
    'SE//EQ',
    'EMLUR',
    'ULLTRALIMPO',
    'JAV',
    'CLEANSTORE',
    'CLINSTORE',
    'REMAX',
    'lugger brasil',
    'SISTEMAS',
    'INDUSTRIAL',
    'CONECTA',
    'CEMAR',
    'ROLIMÃO',
    'WMC REFRIGERAÇÃO',
    'ROMATEC',
    'ARCANT',
    'VIDRAÇARIA ALUMONIO E CIA',
    'BRASRENTEL',
    'FATO PRODUÇÃO',
    'vertical empilhadeira',
    'CARCHER',
    'SDCAR',
    'VIDROS',
    'EDILSON',
    'ZUTINI',
    'ISPE',
    'ANDRADE ANDRADE',
    'hipertec',
    'AIRLAB',
    'P7',
    'AMDINIZ',
    'CAVALCANTI',
    'arqueitetura',
    'topos informatica',
    'KARCHER',
    'Primax',
    'AERO MILE',
    'SOLUÇÕES INDUSTRIAIS',
    'FANNIX',
    'GERADORES',
    'COOLTECH',
    'gestaão patrimonial',
    'pack pack',
    'Recbras',
    'FILMAGEM',
    'BOI',
    'endress',
    'PACKTEC',
    'LAC',
    'SYNTAGMA',
    'ifm eletronic',
    'DISCK TRANS',
    'BLOCOS',
    'PORAQUE',
    'EMBASA',
    'MIGUEL VERJOS',
    'MKALL',
    'krs',
    'MS MANUTENÇAO',
    'METAL MONTE',
    'Inema',
    'MUNCK',
    'LM ENGE',
    'MULTIGÁS',
    'SERRAE COMPANY',
    'POLO ENGENHARIA',
    'previ',
    'FESTIVAL HALELUIA',
    'LABORATORIO LEME',
    'MONTAGENS',
    'municipal sms',
    'NM MOTA REFRIGERAÇAO',
    'É BOM',
    'Mauricio de Nassau',
    'NORDESTE SHP',
    'LATINA',
    'ENGECON',
    'UNIVERSOS',
    'produçoes',
    'TEAM',
    'Net',
    'Nordeste Lubrificantes',
    'ADMICIONAL',
    'CPCON',
    'Solares',
    'TRANSPORTES.',
    'SENSORS AND INSTRUMENTS',
    'CARDAN - NORDESTE',
    'FERG',
    'NK TONEM',
    'AMERICATAMPAS',
    'FAMA',
    'REMOTA',
    'RP',
    'EY',
    'DO BRASIL',
    'SLZ TRANSPORTES',
    'AGUA VIDA',
    'DASART',
    'FC ENGENHARIA',
    'mc',
    'GUEDES TRANSPORTES',
    'labor life',
    'POLI ENGENHARIA',
    'REDE SUPER LEGAL',
    'vistorias',
    'TOTTI EQUIPAMENTOS',
    'TRANSPORTE LOGÍSTICA',
    'ENGENH',
    'MAQUINAS',
    'Gympass',
    'CASA DA MOEDA',
    'merylux',
    'MAN',
    'MEZA ENGENHARIA',
    'NDL',
    'IESP',
    'CASTROSUL',
    'DINAMI',
    'VR  TRANSPORTES',
    'RBR',
    'ARB ENGENHARIA',
    'nove',
    'ALFINIR',
    'RENAUX',
    'ARQUITETURA',
    'JRM',
    'ART LUX',
    'SABARA  QUIMICOS',
    'MARAVILHA MOTOS',
    'fultec',
    'mpt',
    'DCL TRANSPORTE',
    'SOLUÇÃO EM GASES',
    'vagalume eletrico',
    'SEMEC',
    'TERRA',
    'SAUTER',
    'MARQUIZA EVENTOS',
    'TERRABRASIL',
    'SUSTENTABILIDADE',
    'ASSEGH',
    'PERNAMBUCO DISTRIBUIDORA',
    'CRTV',
    'MOTOCAR',
    'tec frio',
    'MUNDIAL LOGISTICAS',
    'BRIM',
    'MADRI EXPRESS',
    'ALEM DO PÃO',
    'MENDES',
    'BLOCK CONSTRUÇÕES',
    'APREVEM CONSULTORIA',
    'coopersucar',
    'SEGURADORA TRANS',
    'AZ - CONSTRUÇÕES',
    'MOVEIS',
    'POSSTAL-LOG',
    'SUDAM',
    'PROXI',
    'AQUAPRO',
    'PRO-LOG',
    'supermix',
    'BORA TRANS',
    'RLTRANSPORTE',
    'COMERCIO',
    'REDE FEMININA',
    'CONSULTORIA SHS',
    'REIS',
    'pallet',
    'termix',
    'RS CAR',
    'antonpa',
    'ecolabi',
    'CSM',
    'SINDICATO DOS BUGGUEIROS',
    'SUPORTE ONIMITRADE',
    'sao jose pinheiro',
    'bahia',
    'MAGNA - LOCAÇÕES',
    'ASSISTERMARCO',
    'MOTOS',
    'ACRILPLAC',
    'RITA',
    'simoes filho',
    'FONTEK SERVIÇOS',
    'ITADUR',
    'BOMBEIRO MILITAR',
    'M.S LOGISTICA',
    'ERNEST YOUNG',
    'ALPHA',
    'EXPRESSOTEC',
    'ARATES',
    'siatemas',
    'TELECOM',
    'PRECISO',
    'JB  TRANSPORTES',
    'CONSULT',
    'luiz',
    'COMELO ENGENHARIA',
    'HOLANDA REFRIGERÇÃO',
    'HERMONT',
    'DRIVEMAX',
    'aertec',
    'Estrategic',
    'engenha',
    'SAGA-TRASPORTES',
    'ALVORADA MOTO',
    'babaçu',
    'correntes cobra',
    'KMJ PRODUÇÕES',
    'AL SOLUÇÕES',
    'ASPEC.ENG.',
    'MA',
    'FETRAMAG',
    'SERVBRASIL',
    'AFC',
    'CENTRAL CAR',
    'AMBREOE',
    'GOOD SERVICE',
    'STEEL',
    'MARSH',
    'ENGEN',
    'AGÊNCIA ESTADUAL DE MEIO AMBIENTE',
    'MCI',
    'S.BUILD',
    'cac-projetos',
    'SBS OUTDOOR',
    '2AP ENGENHARIA',
    '2A',
    'TCMS BRASIL',
    'SEMOB',
    'backman',
    'DACUNHA',
    'OXISOLDAS',
    'SIDEL',
    'ATLAS COOP',
    'MONTERCAL',
    'VJ - AUTOMAÇÃO',
    'NETSZCH',
    'GETRK',
    'INNOVA',
    'BESTPLACE',
    'NCH',
    'MECVED',
    'PAVAX',
    'TORYKS',
    'WJP',
    'SOUZA RANGEL ISOLAMENTOS',
    'TRANSP',
    'ABC COMPRESSORES',
    'INT',
    'CARGA',
    'nova forma',
    'TESLATEC',
    'JANSERV',
    'Metallub',
    'AUTROM - AUTOMAÇÃO',
    'KMTEC',
    'Monta',
    'fellws',
    'MFARTEFATOS',
    'SERILON',
    'GLOBAL',
    'COMPESA',
    'SYSTEM PLASTIL',
    'ALFA OMEGA',
    'JM SERVIÇOES LTDA',
    'KSB',
    'NKA TONER',
    'AQUALUX',
    'REFRAICOL',
    'JR PNEUS',
    'CEPTIS',
    'SHERWIN WILLIANS',
    'GUS DA FESTA',
    'DOT',
    'IDEIA',
    'ABAITI SERVIÇOS',
    'PREDIMEC',
    'SUDIC',
    'IDENTIFICK',
    'RC REFRIGERACAO',
    'MAXSEG',
    'SUAPE ROLAMENTOS',
    'SACMI SACMI',
    'TERUEL',
    'A. Empilhadeira',
    'USIMAN',
    'SOMA TEC',
    'NORDEMEL- HIDROELETRICA',
    'AÇO MA',
    'VP MOTO',
    'DOS PARAFUSOS',
    'RICCO - ALIMENTOS',
    'MCDONALDS',
    'NCR',
    'IRON',
    'LM-CAP',
    'EQUIP',
    'COBEPAL',
    'BEM ESTAR',
    'PSIU INDUSTRIA DE BEBIDAS',
    'TRIX LOG',
    'COINF',
    'MARTIN CIENTIFICA',
    'NORTEL',
    'FRIO PEÇAS',
    'Banner',
    'BRASPRESS',
    'EMAP',
    'G.E Construções e Serviços',
    'BALASKA',
    'VIVER BEM',
    'KARNE KEIJO',
    'TRANSPOR',
    'CITRUS JUICE',
    'SUAPE',
    'COLOSING',
    '3 G. ENGENHARIA',
    'GR/SA',
    'MERCOL',
    'PEF COMERCIO',
    'ASPILL',
    'RODO TRANSPORTES',
    'Eletroflash',
    'ENVASE BR',
    'ELETROVASF',
    'PERFILGRAF',
    'GRANJA ACAI',
    'SoftwareOne.',
    'SHALON REFRIGERAÇÃO',
    'LANCER',
    'DIST - ASSIS',
    'NORDESTE ROLAMENTOS',
    'REALCEMA PLASTICOS',
    'LV TELECON',
    'EMPRESA MAPIAR',
    'LUGER BRASIL',
    'MEGA PEDRAS',
    'Green 4T',
    'TDR ISOLAMENTO E REF.',
    'C. VASQUES',
    'DE PALCO',
    'MM-PLANEJADOS',
    'VIDEO SOFT',
    'CEMEC',
    'EDIS-PRODUÇÕES',
    'Q.A.I. ENGENHARIA',
    'POLI DISEL',
    'EXPRESSO TEC',
    'JY REFEGERAÇÕES',
    'BRASMO',
    'URANOS- EXPRESSO GRAFICA',
    'HAZTEC',
    'ANJELOS',
    'INVERSORES AMERICANA',
    'TAGEM',
    'COMMANDERES',
    'EMPERSOL',
    'MOTIR-ON',
    'GOODYEAR',
    'ITEC',
    'ANGELI',
    'TOP LIMP',
    'MIDIA DIG',
    'ELDER FABIANO',
    'HOME CENTER',
    'JR LOCADORA',
    'SOS',
    'RBS CONTRUÇÕES CIVIS',
    'ESTOFADOS RIBEIRO',
    'JARDINAGEM',
    'COMAPRO AUTOMAÇÃO INDUSTRIAL',
    'HM INSTALAÇÕES',
    'TEMP CLEAN',
    'SUEZ',
    'PWC',
    'FANUC',
    'OWENS',
    'ACEROLIMA',
    'AMBEV',
    'MELO ARQUITETURA',
    'TECFORGEL',
    'ISOLAR',
    'FOCO ENGENHARIA',
    'L.E. NORDESTE',
    'CCC STUDIO',
    'RESCOR',
    'MTX',
    'S. INTELIGENCIA',
    'LASA',
    'CRISTALPET',
    'CASTANHA FESTAS E EVENTOS',
    'HCJ',
    'PLUS MED',
    'Mettler Toledo',
    'NORSUPRI',
    'GRUPO RAVI',
    'ENGENHARI',
    'COATING ENGENHARIA',
    'NE LUBRIFICANTES',
    'FERRO NORTE',
    'USIMETAIS',
    'ACGUA',
    'KEOFITT',
    'VENEZA',
    'XMAK',
    'UNILEVER',
    'BBULL',
    'USINA SERRA GRANDE',
    'ESOERANÇA',
    'CHJ',
    '2AENGENHARIA',
    'AV. ENGENHARIA',
    'KLABIN',
    'TEADIT',
    'arquit',
    'ENGEL COMPANY',
    'PAPA MÍDIA',
    'OURO VERDE',
    'ASA COMUNICAÇÃO',
    'OM SERVICES',
    'APOIO AMBIENTAL',
    'RUSSO NORDESTE',
    'MAYKAEWER',
    'PRODEMIR',
    'MATEUS SUPER',
    'UNINASAL',
    'OLIVEIRA MONTAGENS',
    'SERVICES',
    'Mary Kay',
    'FACULDADE ESTACIO',
    'movex',
    'SRC',
    'HIDRUSCOM',
    'ACS ENG',
    'DENAN',
    'D&A Decoração',
    'ALFA TREINAMENTOS',
    'Rotulo savassa',
    'TWA',
    'KURITA',
    'DANTAS ENG',
    'SERVITEC ENGENHARIA',
    'F.ARAUJO',
    'BRITO Vieira',
    'ELETROMECANICA',
    'BERMO',
    'MENPLAM',
    'TIVIT',
    'REPIPE',
    'Georg Fscher',
    'INDUSERVICE',
    '44',
    'INSTALTEC TECNOLOGIA EM INSTALAÇÕES',
    'ELETROINOX',
    'MALHARIA MIRANTE',
    'VISÃO',
    'BRASIL TINTAS',
    'SEGTEC',
    'PREVEN SEGURANÇA',
    'PROTGE SMS',
    'MUCK',
    'CASCADURA',
    'infinit',
    'P  LOG',
    'SERVCAP',
    'FLATECK',
    'ENGEMELT',
    'ENDUT',
    'CEDROS',
    'LTDA',
    'PRFILGRAF',
    'PLASTIC SOLDA',
    'TRANS DEL',
    'MESA BRASIL',
    'TOYOTAO REBOQUE',
    'SERVICE PACK',
    'GENORMA',
    'CASA',
    'RPA   TRANSPORTES',
    'FENGSEG',
    'PINHEIRO',
    'ZEUS ELETRICA',
    'metrohm',
    'PV ENGENHARIA',
    'ESPIRAL',
    'DT TECNO. ELETRONICAS',
    'ELETROCENTER',
    'tecban',
    'ASUSU FILMAGENS',
    'ANTON PAR',
    'IAVECHAMAR',
    'ENGE',
    'VIRGILANCIA SANITARIA DA BAHIA',
    'MARINE',
    'LUMINAR',
    'FOCO MACHINE EXPRESS',
    'TELENSAT',
    'ECOFRIO',
    'mcfal',
    'TRAÇÃO',
    'CARVALHO CONSULTORIA',
    'center motos',
    'SHNEIDER ELECTRIC',
    'locah',
    'B& S - AUTOMAÇÃO',
    'Solution',
    'MONTANA',
    'MAYEKAWA',
    'JCTM',
    'ML Guindaste',
    'RCA',
    'FOCO',
    'DWA ENG',
    'NAC.Guinchos',
    'HIGHEND',
    'SERVICOM',
    'METALURGICA VALENTE',
    'Spraying System',
    'MA BEVERAGE',
    'DOURO ENGENHARIA',
    'HITA - COMERCIO E SERVIÇOS',
    'HIDROCON',
    'VPA AUTOMAÇÃO',
    'USINA TRAPICHE',
    'MOTIR - ON',
    'ALLSTEEL',
    'AERO ARQ',
    'SHIFT POWER',
    'eg muck',
    'KECHER',
    'DITRIBUIÇÃO',
    'PREDIMIX',
    'USICOM',
    'TREINAMENTOS',
    'REFRESCOS GUARARAPES LTDA',
    'NORSA REFRIGERANTES SA',
    'CAF - CRYSTAL AGUAS DO NORDESTE LTDA',
    'SOLAR BEBIDAS SA',
    'Policial',
    'SOLAR',
    'Cab',
    'R&M Tecnologia',
    'FANTASIA TESTE',
    'CPRH',
    'VIDEOJET',
    'MAXIMO SMS',
    'SAIF CLIMATIZAÇÃO SERVIÇOS E VENDAS DE PEÇAS',
    'AIRES',
    'TS GUINCHO',
    'NTN BRASIL',
    'NTN',
    'VIDEO SEGURANÇA',
    'IMPACTO SONORIZACOES',
    'SS CONSTRUÇÕES',
    'ISNADIA OLIVEIRA SOUSA',
    'WORKTEC',
    'SOARES LEAL',
    'THIGO OLIVEIRA DECOR.',
    'ECOL',
    'ALCAM INDUSTRIAL',
    'DL GUINCHO E CONTAINER',
    'valgroup',
    'ZEGLA',
    'COIOTE SEGURANÇA ELETRONICA',
    'LV EVENTOS',
    'DJ CARLOS  MASSA',
    'HIDROS COMERCIO LTDA',
    'INFRALINK',
    'TDI',
    'BOM FIM ENGENHARIA',
    'FIBRASA',
    'MCR',
    'PRORAD',
    'MANISA',
    'SIL',
    'CHNUT',
    'MIURA',
    'ECOMONTAGEM',
    'GRUPOFORT',
    'RENTOKIL',
    'WHITE MARTINS',
    'BRASANITAS',
    'GRUPO FORTE',
    'SAIF',
    'JURUA MOTOS',
    'MOTOBEL',
    'MOV LOG',
    'SILVANO E SILAVO',
    'HMPC',
    'MULTISERVICE',
    'EM DA SILVA SERVICOS ME',
    'ACCENTURE',
    'RECICLATE',
    'USINAFA',
    'AUTECMA',
    'B&F DIAS',
    'SOLAR BR',
    'TRACTIAN',
    'LOW CAST',
    'FERGAL',
    'Culture Filmes',
    'TUNAP',
    'LAX',
    'CYKLOP',
    'RS ROSENDO',
    'Construprev',
    'REUNAX - SERVICE',
    'Jose Robson Vieira da Silva',
    'Holanda Refrigeracao',
    'MIB ARMAZENS',
    'CLINERGY',
    'TPF',
    'ST-ONE',
    'GN TRANSPORTES',
    'METALUNOX',
    '3D CRIAR',
    'QUEO NETICS',
    'TECNOVAL',
    'NSK',
    'SF ENGENHARIA',
    'ROMELEVA',
    'PISANI',
    'SERCOS NORDESTES',
    'AMBIPAR',
    'INTERLUB',
    'OCS INSTALAÇÕES INDUSTRIAIS',
    'TELMEX',
    'INVICTA',
    'MYSNARSKI',
    'QUALITEX',
    'Bradesco PAB',
    'CENTRAL DE RESIDUOS',
    'ARSEG',
    'TRIXLOG',
    'sesi saude',
    'RS MANGUEIRAS',
    'ALESSANDRE ANDRADE ARQUITETURA ENGENHARIA',
    'ORGUEL',
    'JH ENGENHARIA',
    'O POSITIVO',
    'WORKSAFE',
    'JML',
    'AGISA',
    'HM INSTALAÇÕES INDUSTRAIS',
    'SILVANO E SILVANO',
    'ARAUJO ABREU ENGENHARIA NORTE',
    'BUILDMARK',
    'PARAGUAÇU ENGENHARIA',
    'BLOWER',
    'SICK',
    'CNPJ / CPF',
    'INFRAESTRUTURA',
    'NORTE VALVULAS',
    'HIDROSAM',
    'TEC GAS',
    'SAMSON',
    'MAGMA',
    'TDM',
    'CIDADE LIMPA',
    'PAPEL E CIA PRODUTOS DE PAPELARIAS LTDA',
    'SS EXPRESSO',
    'TSI',
    'Grupo Simoes',
    'RST',
    'ICONE',
    'MILENA PAIVA',
    'BIEL MOTOS',
    'FS LOG',
    'ASIAN COMPANY',
    'CALMAN',
    'ACM',
    'PHX',
    'ANA LUCIA',
    'COMERCIAL YOKOYAMA',
    'BRASCOLOR GRAFICA E EDITORA',
    'MONITORA',
    'XPA ENGENHARIA',
    'NACIONAL GAS',
    'MULTINORTE',
    'JAPA PRINT',
    'ENGEBANK',
    'BELNAVE',
    'AV FARIAS',
    'GNV',
    'TALENT',
    'NETPRIMUS',
    'ABRAZON',
    'MULTI ANALISES',
    'PIAUI SAFETY',
    'DISA',
    'GAS METAL',
    'ALFA METAL',
    'PARAMUCK',
    'COSTA E CARVALHO COMERCIO',
    'ATLAS COPCO',
    'SCHMERSAL',
    'ESTILO MANUTENCAO',
    'DISBRAVA',
    'FRUTEX',
    'ENJOY',
    'HEINEKEIN',
    'VGA',
    'CSC',
    'M&Y TRANSPORTE',
    'PARA FERRO',
    'SYNTHOIL',
    'MOTORGEL',
    'STELA',
    'MARFRIO',
    'ASA CONSTRUTORA',
    'CARBOMAN',
    'MENTEC',
    'RBT',
    'DURBETON',
    'LUX PLACAS',
    'LEMAR',
    'RESISTENCIA',
    'ACRILUX',
    'EAGLE ELETRICA',
    'EGUILHERME',
    'MAKO',
    'LEGALISA',
    'GOLD ENGENHARIA',
    'CENTURY',
    'RODOVITOR TRANSPORTES E LOC VEIC',
    'DENIS GROUP',
    'BRAGA CONSULTORA',
    'PLATINOX COMERCIO DE EQUIPAMENTOS',
    'ATUAL CARGA',
    'IMPERSIK',
    'GUERCIA CONSULTORIA',
    'GEDOR',
    'ROBOPAC',
    'UNIQUE',
    'MIRA',
    'VARANDA',
    'KINGSPAH',
    'AIRLIQUIDE',
    'TRATOMAR',
    'SERVPACK',
    'HIDRADYNE',
    'JUMP',
    'PAGUE MENOS',
    'MAIS GAS',
    'FLUSSO',
    'JD SERVIÇOS DE ENGENHARIA',
    'AUTO DEFESA BRASIL',
    'NLOG',
    'SCARF',
    'AZIMUTE',
    'SOVEDAÇÕES',
    'ESTILOS MANUTENÇÕES',
    'PERFET',
    'BERTOLINI',
    'COBERTURA E CIA',
    'FC',
    'BRADO',
    'CRETA',
    'AMP',
    'INOVA',
    'THAYRONECELL',
    'MEDSAFE',
    'ABZ SEGURANÇA',
    '2 DUO TRANSPORTE LTDA',
    'NASCIONAL GAS',
    'GR SA',
    'HALLER CONSULTORIA E RECURSOS HUMANOS LTDA',
    'QUIMICA CREDI',
    'LONGA ARMAZENAGEM',
    'trans paulistana',
    'LCC',
    'MB',
    'P MAS',
    'SR ENGENHARIA',
    'MENGONI',
    'ALUCEL',
    'INOX MARANHÃO',
    'Coplast Industria Química LTDA',
    'ENVIRONMENT BRASIL',
    'BEVAP',
    'PRONTO PLACA',
    'VALE AUTOMAÇÃO',
    'CONSTRUTORA EBERIK',
    'MECATRON',
    'MAKO ENGENHARIA',
    'MARCO ENGENHARIA',
    'R CONSULT',
    'RAÇA TRANSPORTE',
    'FERRALTEC',
    'BRASIL AUTO CENTER',
    'ENGESTEAM',
    'KAMPER',
    'BARUFALDI',
    'AMAZON ELETRICA',
    'IPHONE LENDEL CELL',
    'HELIOP',
    'ALO SERVICE',
    'E3FIX ENGENHARIA',
    'DRJ TRANSPORTES',
    'SIMIC',
    'GUNTNER',
    'TELEMATICA',
    'ISHIDA BRASIL',
    'BALL',
    'AUTOMATIZA',
    'ANALITICA',
    'COMANDO  METAL',
    'PREDICT',
    'CORPORATIVO',
    'CLARO S.A',
    'TORNEADORA AGAPE',
    'RESISTENCIA CONSULTORIA',
    'JF MULTI SERVIÇO',
    'GRS',
    'STM',
    'ESMATEC',
    'AGILETECH',
    'STAE ENGENHARIA LTDA',
    'cas',
    'INSTRUVAL',
    'TRANSOL',
    'ssma engenharia',
    'METRICA',
    'CASA DOS FILTROS',
    'BSP',
    'TECNOISO',
    'TRANSPAULISTANA',
    'HOMI AUTOMAÇÃO',
    'RENE MANUTENÇÃO',
    'TBA TRANSPORTES',
    'GE LOGISTICATK',
    'SCAN SOLO',
    'BELÉM TELHAS',
    'GEMO',
    'EXTINOVA',
    'LEMOS ENERGIA',
    'RAÇA',
    'LS PACK SERVICE',
    'CROWN',
    'TRANSDOURADA',
    'LJ MONTAGENS',
    'UNITECH',
    'PHOTO HAPPY',
    'RANGER SMS',
    'EB PROJETOS',
    'FORTE REAL',
    'A2 ENGENHARIA',
    'GEP',
    'GOVERNO DO ESTADO',
    'BENTOBRASIL',
    'VILI LOGISTICA',
    'policia',
    'ANHAGUERA',
    'SOLUCAPS',
    'QUEIROZ',
    'VCA CONSTRUTORA',
    'UNIRIOS',
    'GR Segurança',
    'Santys Produções',
    'ALTO PADRÃO  ENGENHARIA E TECNOLOGIA LTDA',
    'CRC',
    'INSTITUTO EMBELLEZE',
    'ASEMTE',
    'ROLAMENTOS CBF',
    'MANUTROL',
    'BATISTI TRANSPORTES',
    'SAPORIUM',
    'SODEXO',
    'FOX',
    'WB REFRIGERAÇÃO',
    'JP ENGENHARIA',
    'TEC ELETRICA',
    'Cruz Engearia',
    'TRANSCABRAL LTDA',
    'LEMOS PASSOS',
    'SERLARES',
    'SR EMBALAGENS',
    'CONECTE VOIP',
    'STA',
    'ENGEL ENGEARINHA',
    'IBC QUALIDADE',
    'MOAS',
    'MARP',
    'APTEC',
    'CAL SERVICE',
    'LISBOA',
    'ENGEPACK',
    'BEECORP',
    'KIS',
    'SENA & SANTOS',
    'ipersik',
    'LAGUA DOCE',
    'COMPAR RIO BRANCO',
    'SAP',
    'GLOBAL STANDARDES',
    'AST GUINDASTE',
    'EVIDENCIA LOGISTICA',
    'SEGUPRO',
    'SINI BAHIA',
    'construtora renova',
    'EQUATORIAL',
    'AMPI UNIFORMES',
    'NORTEC',
    'GUERCIA',
    '7 COM SERVICOS',
    'VIRGINIA MENDONÇA',
    'BALTECH',
    'DALLAS ARQUITETURA',
    'NOVO CICLO',
    'INTERGLESS',
    'ACS ENGENHARIA',
    'PILZ',
    'MONFAE',
    'LC ENGENHARIA',
    'INSTITUTO LIXO ZERO',
    'BR NORTE',
    'TRACTION',
    'A S SERVIÇOS',
    'COELHO VOIP',
    'EGS SERVICOS',
    'J CAMARGO ALTOMAÇÃO',
    'TOTAL SERVIÇO',
    'MAXSERV',
    'JUNGHEINRICH LIFT TRUCK',
    'MART PRINT',
    'ARAUJO OLIVEIRA',
    'IPIRANGA',
    'ZILQUIMICA',
    'COMPAR',
    'UNIÃO TRANSPORTES',
    'CONEC',
    'REBOKIT',
    'SARDO',
    'AB SERVIÇOS',
    'SYSTENS',
    'PRÁTICA',
    'DELTAMAQ',
    'H2Q',
    'VC2 RECURSOS HUMANOS',
    'RC TRANSPORTES',
    'WANS FARIAS',
    'COGTIVE',
    'ATIVA',
    'CARGO POLO',
    'AF TRABSPORTES',
    'UNIAO MULTIMODAL',
    'SALES ALMEIDA',
    'GE LOGISTICA',
    'VIA NORTE  LTDA',
    'PEREIRA LIMA',
    'RODOJUNIOR',
    'COMRANÇA',
    'COMFRANÇA',
    'EXPRESSO GERAÇÃO',
    'TGR',
    'TRANSWAC',
    'CTS TRANSPORTADORA',
    'PL',
    'USINA PETRIBU',
    'AGREGA MAIS',
    'RODOCELL TRANSPORTES E LOGISTICA',
    'EXPRESSO GERAÇÃO TRANPORTES',
    'FONTE D VIDA',
    'USINA ESTIVAS',
    'CONEXLOG',
    'HAPVIDA',
    'TREMEA',
    'SAFETECH IT',
    'ROSSO NORDESTE',
    'A M QUIMICA',
    'AZIMUTECH',
    'VITAL',
    'ULTRALOG',
    'ARMANI',
    'HYTEC',
    'CASA DOS ROLAMENTOS',
    'SUPER SONIC TRANSPORTES',
    'ROL PAF',
    'RAC',
    'META TRUCK',
    'EDIMETAL',
    'ANGELUS',
    'SAMPRED',
    'PREÇO BOM',
    'FACCHINI',
    'JERTMONT',
    'FINATTO',
    'SUSTENTARE',
    'ENSEI',
    'GABCO',
    'ENGEUS',
    'MEY TRANSPORTES',
    'RAVIBRAS',
    'RAPIDO FIGUEIREDO',
    'BSP TRANSPORTES',
    'AMAZONGAS',
    'YAMAMOTO',
    'PROTECNICA',
    'MAMUTH',
    'FERTÉCNICA',
    'DUNLOC',
    'DONALDSON',
    'QUINTAS COMUNICAÇÕES',
    'INVISTA',
    'CIGAS',
    'CYLTEST',
    'aledcor',
    'PARATY BEBIDAS',
    'INVITA',
    'FAST MONITORAMENTO E RASTREAMENTO VEICULAR',
    'ALTA PADRÃO ENG',
    'H S HAURADOU SISTEMAS',
    'Pp&C Auditores Independentes',
    'ADUKARGO',
    'ARKO SOLUCOES',
    'OMEGA NORTE',
    'DISMACON',
    'CAMPARI',
    'GELADOCE',
    'TEKNOFIK',
    'HILTI',
    'SETE COMERCIO E SERVICOS DE PNEUS LTDA',
    'ALE DECOR',
    'ALTO PADRAO ENGENHARIA',
    'METAL NOBRE',
    'COBAP',
    'ENTREGA ALMOXARIFADO',
    'A L C CAR SERVIÇOS',
    'HU',
    'MONACO MOTOCENTER',
    'NORTE MANUTENÇÃO',
    'NORTE SERVICE REFRIGERAÇÃO INDUSTRIAL LTDA',
    'RAÇA TRANS',
    'RR SERVIÇO',
    'CARDINALI BOMBAS',
    'SIL - MAGRI MANUTENCAO',
    'CONSTRUTORA E INCORPORADORA CORREIA & PEIXOTO LTDA',
    'BRADESCO  FVAG',
    'G R S A Serviços e Alimentacao LTDA',
    'HITSS DO BRASIL',
    'INTERATIVA EMPREENDIMENTOS',
    'Marina Queiroz',
    'Marina QPRTC',
    'TOPLINE',
    'CHICO TOUR TRANSPORTES EIRELI',
    'LIDERANCA LOGISTICA',
    'PORTO MOTOS',
    'PROGUARDA',
    'SAGA EQUIPAMENTOS E SIRVICOS EIRELI',
    'BANCO BRADESCO',
    'EM DA SILVA SERVICOS  ME',
    'SERVICE LOG',
    'NOVA SANTANA',
    'PROTEMAXI SEGURANÇA',
    'DIVERSEY BRASIL',
    'TRIX  log',
    'OSVALDO MIGUEL NEVES',
    'JARAQUI AUTOMATION LTDA',
    'CASTRO INDUSTRIAL',
    'TOKO TUBULACOES',
    'ISOLAR',
    'solar',
    'MONACO',
    'AUTONOMO',
    'solar arruda',
    'SERCOM EQUIPAMENTOS',
    'GRUPO LOUZA',
    'MANAUS DUTOS',
    'saimq',
    'MICRO-LAB',
    'SANTA ROSA',
    'AURORA LIVE MARKETING E EVENTOS LTDA',
    'M P DE SOUZA PONTES',
    'entrega',
    'MILLA TRANSPORTES',
    'OKAMOTO FLORES',
    'SEM EMPRESA',
    'construções amazonicas',
    'Teste de CNPJ',
    'cadastrando',
    'COLETA AUTOS',
    'PRECO BOM',
    'AMAZON CLEAN',
    'MZT CARGAS',
    '4 IRMAOS',
    'TRANSPORTE RODOVIARIO',
    'DWA ENGENHARIA',
    'El Condor',
    'HD LOGISTICA',
    'PALLETS BN',
    'segvieg',
    'CRISTAL ENGENHARIA',
    'sovel',
    'Robotersys',
    'KRONES DO BRASIL LTDA',
    'CROWN EMBALAGENS',
    'CONSTRUTORA ASA',
    'FC ENGENHARIA',
    'G&P ENGENHARIA',
    'POWER CLEAN',
    'a ELLOS SERVICOS AGENCIAMENTOS E TRANSPORTES DE CARGAS LTDA',
    'ellos refrigeração',
    'AMG Policlínica',
    'INTERATIVA',
    'SUZANO',
    '5001 TRANSPOTE',
    'PRESTEX ENCOMENDAS',
    'BALL BEVERAGE - ENTREGA',
    'SANITECK - POLISYSTEM SERVICO DE APOIO ADMINISTRATIVO LTDA',
    'MASTERFRIGO',
    'PL TRANSPORTES',
    'VALTECHE',
    'ZIEL ENGENHARIA',
    'GUIANOL',
    'SEST SENAT',
    'MIMAKI',
    'KALYKIM',
    'RECICLAGEM O NANDO',
    'NORTEMATIC',
    'NORTE MOTORES',
    'Majorseg',
    'RAMSONS',
    'PAULO VERAS SMS',
    'SUPERIOR TRANSPORTES LOCACAO E LOGISTICA LTDA',
    'LYON H ALVES ME',
    'Protemaxi Segurança Patrimonial Armada Eireli',
    'Interativa Empreendimentos e Servicos de Limpeza e Construcoes LTDA',
    'FACI WIDEM',
    'PANOSSI',
    'Interativa Empreendimentos e Servicos de Limpeza e Construcoes LTDA',
    'Technofrio Refrigeração',
    'SEMUSA',
    'MESQUITA ENGENHARIA',
    'ENGSHS',
    'K S NUNES',
    'DISA ECO',
    'JANSERV',
    'GRSEGURANCA',
    'RBT-CLIMAIZACAO',
    'RCR LOCACAO',
    'GR-ALIMENTACAO',
    'BRASALPLA BRASIL - INDUSTRIA DE EMBALAGENS LTDA',
    'UPTRON COMERCIO IMPORTACAO E EXPORTACAO LTDA',
    'PMAIS',
    'METRON PRODUÇÕES LTDA',
    'UNIR - UNIVERSIDADE FEDERAL DE RONDONIA',
    'Mancos Antonio',
    'Rafael Herreira',
    'Moisés',
    'COOPERCARGA',
    'PERNAMBUCO CONSTRUTORA',
    'GL ACABAMENTOS',
    'Christopher Pereira Teles',
    'UNAMA',
    'FORMATO TRANSPORTES',
    'ALUTEC',
    'DAYCA',
    'ZETALOC',
    'DINIZ TRANSPORTES',
    'SIRROS',
    'Solar Engenharia',
    'DESTAK',
    'SALVADOR',
    'MPM ALUGUEL DE AR',
    'AZZE',
    'VGE',
    'PROJEART',
    'JC TRANSPORTES',
    'MECESA',
    'RIFAS',
    'PASSARO TRANSPORTES',
    'T&R DE TAMONTI',
    'DMS MANUTENCAO',
    'SM MONTAGEM',
    'CDG SOLUTIONS',
    'SANITY FIRE',
    'SEBRAE',
    'EVR',
    'MUSSNICH',
    'GM TRANSPORTES',
    'PEDRO SOARES DE SOUZA MOBILIARIOS',
    'MD VIDRAÇARIA',
    'FUTURA',
    'JSL'
  ].sort();

  const unidades = ['ARD', 'BEL', 'BLM', 'CRR', 'DMU', 'FOR', 'JGS', 'JPA', 'MAO', 'MCZ', 'NAT', 'OCZ', 'PVH', 'RET', 'SLZ', 'SSA', 'SUA', 'THE', 'VAG', 'VDC'].sort();
  
  const grupos = ['R1', 'R2', 'R3'].sort();
  
  const setores = [
    'Comercial',
    'CSC',
    'DISTRIBUICAO',
    'EQS / GDM',
    'ESTOQUE / ALMOXARIFADO',
    'EXPEDICAO',
    'FROTA',
    'INFRAESTRUTURA',
    'LIMPEZA E JARDINAGEM',
    'LOGISTICA',
    'MAN. AUTOS',
    'MANUTENCAO INDUSTRIAL',
    'MANUTENCAO PREDIAL',
    'MARKETING',
    'MEIO AMBIENTE',
    'PORTARIA E SEG. PATRIMONIAL',
    'PRINT IN HOUSE',
    'PRODUCAO',
    'QUALIDADE',
    'RECICLAGEM',
    'REFEITORIO',
    'Residuos',
    'SEGURANCA DO TRABALHO'
  ].sort();

  const formatCPF = (value: string) => {
    const numbers = value.replace(/\D/g, '');
    if (numbers.length <= 11) {
      return numbers.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, '$1.$2.$3-$4');
    }
    return value;
  };

  const formatCNPJ = (value: string) => {
    const numbers = value.replace(/\D/g, '');
    if (numbers.length <= 14) {
      return numbers.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, '$1.$2.$3/$4-$5');
    }
    return value;
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    
    const newCollaborator: Collaborator = {
      id: Date.now().toString(),
      nomeCompleto: formData.get('nomeCompleto') as string,
      cpf: formData.get('cpf') as string,
      empresa: formData.get('empresa') as string,
      cnpj: formData.get('cnpj') as string || '',
      novaEmpresa: formData.get('novaEmpresa') as string || '',
      unidade: formData.get('unidade') as string,
      grupo: formData.get('grupo') as string,
      setor: formData.get('setor') as string,
      gestor: formData.get('gestor') as string,
      integracao: formData.get('integracao') ? new Date(formData.get('integracao') as string) : null,
      aso: formData.get('aso') ? new Date(formData.get('aso') as string) : null,
      nr10: formData.get('nr10') ? new Date(formData.get('nr10') as string) : null,
      nr10Sep: formData.get('nr10Sep') ? new Date(formData.get('nr10Sep') as string) : null,
      nr11: formData.get('nr11') ? new Date(formData.get('nr11') as string) : null,
      nr12: formData.get('nr12') ? new Date(formData.get('nr12') as string) : null,
      nr18: formData.get('nr18') ? new Date(formData.get('nr18') as string) : null,
      nr18Andaime: formData.get('nr18Andaime') ? new Date(formData.get('nr18Andaime') as string) : null,
      nr20: formData.get('nr20') ? new Date(formData.get('nr20') as string) : null,
      nr33: formData.get('nr33') ? new Date(formData.get('nr33') as string) : null,
      nr35: formData.get('nr35') ? new Date(formData.get('nr35') as string) : null,
      nr34: formData.get('nr34') ? new Date(formData.get('nr34') as string) : null,
      pgroPcmat: formData.get('pgroPcmat') ? new Date(formData.get('pgroPcmat') as string) : null,
      pcmso: formData.get('pcmso') ? new Date(formData.get('pcmso') as string) : null,
      ppr: formData.get('ppr') ? new Date(formData.get('ppr') as string) : null,
      loto: formData.get('loto') ? new Date(formData.get('loto') as string) : null,
      ptaPlataforma: formData.get('ptaPlataforma') ? new Date(formData.get('ptaPlataforma') as string) : null,
      treinamento: formData.get('treinamento') === 'on',
      os: formData.get('os') === 'on',
      documentacao: formData.get('documentacao') === 'on',
      aprPae: formData.get('aprPae') === 'on',
      epi: formData.get('epi') === 'on',
      cipa: formData.get('cipa') === 'on',
    };

    setCollaborators(prev => [...prev, newCollaborator]);
    
    toast({
      title: "Colaborador adicionado",
      description: "Colaborador adicionado com sucesso!",
    });

    // Reset form
    (e.target as HTMLFormElement).reset();
  };

  const handleDownloadCSV = () => {
    if (collaborators.length === 0) {
      toast({
        title: "Erro",
        description: "Adicione pelo menos um colaborador antes de baixar o CSV.",
        variant: "destructive",
      });
      return;
    }

    const csvHeader = "Nome Completo,CPF,Empresa,CNPJ,Nova Empresa,Unidade,Grupo,Setor,Gestor,Integração,ASO,NR10,NR10-SEP,NR11,NR12,NR18,NR18 Andaime,NR20,NR33,NR35,NR34,PGRO/PCMAT,PCMSO,PPR,Loto,PTA Plataforma,Treinamento,OS,Documentação,APR/PAE,EPI,CIPA\n";
    
    const csvData = collaborators.map(c => {
      const formatDateForCSV = (date: Date | null) => date ? format(date, 'dd/MM/yyyy') : 'null';
      const formatBooleanForCSV = (value: boolean) => value ? 'Sim' : 'Não';
      
      return [
        `"${c.nomeCompleto}"`,
        `"${c.cpf}"`,
        `"${c.empresa}"`,
        `"${c.cnpj || ''}"`,
        `"${c.novaEmpresa || ''}"`,
        `"${c.unidade}"`,
        `"${c.grupo}"`,
        `"${c.setor}"`,
        `"${c.gestor || 'null'}"`,
        `"${formatDateForCSV(c.integracao)}"`,
        `"${formatDateForCSV(c.aso)}"`,
        `"${formatDateForCSV(c.nr10)}"`,
        `"${formatDateForCSV(c.nr10Sep)}"`,
        `"${formatDateForCSV(c.nr11)}"`,
        `"${formatDateForCSV(c.nr12)}"`,
        `"${formatDateForCSV(c.nr18)}"`,
        `"${formatDateForCSV(c.nr18Andaime)}"`,
        `"${formatDateForCSV(c.nr20)}"`,
        `"${formatDateForCSV(c.nr33)}"`,
        `"${formatDateForCSV(c.nr35)}"`,
        `"${formatDateForCSV(c.nr34)}"`,
        `"${formatDateForCSV(c.pgroPcmat)}"`,
        `"${formatDateForCSV(c.pcmso)}"`,
        `"${formatDateForCSV(c.ppr)}"`,
        `"${formatDateForCSV(c.loto)}"`,
        `"${formatDateForCSV(c.ptaPlataforma)}"`,
        `"${formatBooleanForCSV(c.treinamento)}"`,
        `"${formatBooleanForCSV(c.os)}"`,
        `"${formatBooleanForCSV(c.documentacao)}"`,
        `"${formatBooleanForCSV(c.aprPae)}"`,
        `"${formatBooleanForCSV(c.epi)}"`,
        `"${formatBooleanForCSV(c.cipa)}"`
      ].join(',');
    }).join('\n');

    const csvContent = csvHeader + csvData;
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    
    if (link.download !== undefined) {
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `colaboradores_${format(new Date(), 'dd-MM-yyyy')}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
    
    toast({
      title: "CSV baixado",
      description: "O arquivo CSV foi baixado com sucesso!",
    });
  };

  const removeCollaborator = (id: string) => {
    setCollaborators(prev => prev.filter(c => c.id !== id));
    toast({
      title: "Colaborador removido",
      description: "Colaborador removido com sucesso!",
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-8">
      <div className="container mx-auto px-4 space-y-8">
        {/* Header with back button */}
        <div className="flex items-center gap-4 mb-6">
          <Link to="/" className="flex items-center gap-2 text-blue-600 hover:text-blue-800">
            <ArrowLeft className="h-5 w-5" />
            Voltar para versão React
          </Link>
        </div>

        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold text-gray-900">
            Controle de Vencimentos - Versão HTML5
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Sistema alternativo em HTML5 para cadastramento e controle das datas de vencimento
          </p>
        </div>

        {/* HTML5 Form */}
        <Card className="w-full max-w-6xl mx-auto">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Plus className="h-5 w-5" />
              Adicionar Colaborador (HTML5)
            </CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Dados Pessoais */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold">Dados Pessoais</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label htmlFor="nomeCompleto" className="text-sm font-medium">Nome Completo *</label>
                    <input
                      id="nomeCompleto"
                      name="nomeCompleto"
                      type="text"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                      placeholder="Nome completo do colaborador"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="cpf" className="text-sm font-medium">CPF *</label>
                    <input
                      id="cpf"
                      name="cpf"
                      type="text"
                      required
                      maxLength={14}
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                      placeholder="000.000.000-00"
                      onInput={(e) => {
                        const input = e.target as HTMLInputElement;
                        input.value = formatCPF(input.value);
                      }}
                    />
                  </div>
                </div>
              </div>

              {/* Dados Organizacionais */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold">Dados Organizacionais</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div className="space-y-2">
                    <label htmlFor="empresa" className="text-sm font-medium">Empresa *</label>
                    <select
                      id="empresa"
                      name="empresa"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <option value="">Selecionar empresa</option>
                      {empresas.map((empresa) => (
                        <option key={empresa} value={empresa}>
                          {empresa}
                        </option>
                      ))}
                     </select>
                   </div>
                 </div>
                 
                 {/* Segunda linha - CNPJ e Nova Empresa */}
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                   <div className="space-y-2">
                     <label htmlFor="cnpj" className="text-sm font-medium">CNPJ</label>
                     <input
                       id="cnpj"
                       name="cnpj"
                       type="text"
                       maxLength={18}
                       className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                       placeholder="00.000.000/0000-00"
                       onInput={(e) => {
                         const input = e.target as HTMLInputElement;
                         input.value = formatCNPJ(input.value);
                       }}
                     />
                   </div>
                   <div className="space-y-2">
                     <label htmlFor="novaEmpresa" className="text-sm font-medium">Nova Empresa</label>
                     <input
                       id="novaEmpresa"
                       name="novaEmpresa"
                       type="text"
                       className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                       placeholder="Nome da nova empresa"
                     />
                   </div>
                 </div>

                 {/* Terceira linha - Dados organizacionais */}
                 <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                   <div className="space-y-2">
                     <label htmlFor="unidade" className="text-sm font-medium">Unidade *</label>
                    <select
                      id="unidade"
                      name="unidade"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <option value="">Selecionar unidade</option>
                      {unidades.map((unidade) => (
                        <option key={unidade} value={unidade}>
                          {unidade}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="grupo" className="text-sm font-medium">Grupo *</label>
                    <select
                      id="grupo"
                      name="grupo"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <option value="">Selecionar grupo</option>
                      {grupos.map((grupo) => (
                        <option key={grupo} value={grupo}>
                          {grupo}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="setor" className="text-sm font-medium">Setor *</label>
                    <select
                      id="setor"
                      name="setor"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <option value="">Selecionar setor</option>
                      {setores.map((setor) => (
                        <option key={setor} value={setor}>
                          {setor}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="gestor" className="text-sm font-medium">Gestor</label>
                    <input
                      id="gestor"
                      name="gestor"
                      type="text"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                      placeholder="Nome do gestor"
                    />
                  </div>
                </div>
              </div>

              {/* Datas de Vencimento */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold">Datas de Vencimento</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div className="space-y-2">
                    <label htmlFor="integracao" className="text-sm font-medium">Integração *</label>
                    <input
                      id="integracao"
                      name="integracao"
                      type="date"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="aso" className="text-sm font-medium">ASO *</label>
                    <input
                      id="aso"
                      name="aso"
                      type="date"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr10" className="text-sm font-medium">NR10</label>
                    <input
                      id="nr10"
                      name="nr10"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr10Sep" className="text-sm font-medium">NR10-SEP</label>
                    <input
                      id="nr10Sep"
                      name="nr10Sep"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr11" className="text-sm font-medium">NR11</label>
                    <input
                      id="nr11"
                      name="nr11"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr12" className="text-sm font-medium">NR12</label>
                    <input
                      id="nr12"
                      name="nr12"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr18" className="text-sm font-medium">NR18</label>
                    <input
                      id="nr18"
                      name="nr18"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr18Andaime" className="text-sm font-medium">NR18 Andaime</label>
                    <input
                      id="nr18Andaime"
                      name="nr18Andaime"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr20" className="text-sm font-medium">NR20</label>
                    <input
                      id="nr20"
                      name="nr20"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr33" className="text-sm font-medium">NR33</label>
                    <input
                      id="nr33"
                      name="nr33"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr35" className="text-sm font-medium">NR35</label>
                    <input
                      id="nr35"
                      name="nr35"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="nr34" className="text-sm font-medium">NR34</label>
                    <input
                      id="nr34"
                      name="nr34"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="pgroPcmat" className="text-sm font-medium">PGRO/PCMAT *</label>
                    <input
                      id="pgroPcmat"
                      name="pgroPcmat"
                      type="date"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="pcmso" className="text-sm font-medium">PCMSO *</label>
                    <input
                      id="pcmso"
                      name="pcmso"
                      type="date"
                      required
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="ppr" className="text-sm font-medium">PPR</label>
                    <input
                      id="ppr"
                      name="ppr"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="loto" className="text-sm font-medium">Loto</label>
                    <input
                      id="loto"
                      name="loto"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="ptaPlataforma" className="text-sm font-medium">PTA Plataforma</label>
                    <input
                      id="ptaPlataforma"
                      name="ptaPlataforma"
                      type="date"
                      className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    />
                  </div>
                </div>
              </div>

              {/* Documentação Adicional */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold">Documentação Adicional</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  <div className="flex items-center space-x-2">
                    <input
                      id="treinamento"
                      name="treinamento"
                      type="checkbox"
                      className="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground"
                    />
                    <label htmlFor="treinamento" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                      Treinamento
                    </label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <input
                      id="os"
                      name="os"
                      type="checkbox"
                      className="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground"
                    />
                    <label htmlFor="os" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                      OS
                    </label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <input
                      id="documentacao"
                      name="documentacao"
                      type="checkbox"
                      className="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground"
                    />
                    <label htmlFor="documentacao" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                      Documentação
                    </label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <input
                      id="aprPae"
                      name="aprPae"
                      type="checkbox"
                      className="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground"
                    />
                    <label htmlFor="aprPae" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                      APR/PAE
                    </label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <input
                      id="epi"
                      name="epi"
                      type="checkbox"
                      className="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground"
                    />
                    <label htmlFor="epi" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                      EPI
                    </label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <input
                      id="cipa"
                      name="cipa"
                      type="checkbox"
                      className="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground"
                    />
                    <label htmlFor="cipa" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                      CIPA
                    </label>
                  </div>
                </div>
              </div>

              <Button type="submit" className="w-full">
                <Plus className="mr-2 h-4 w-4" />
                Adicionar Colaborador
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Simple List of Added Collaborators */}
        {collaborators.length > 0 && (
          <Card className="w-full max-w-6xl mx-auto">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4">
              <CardTitle>Colaboradores Adicionados ({collaborators.length})</CardTitle>
              <Button onClick={handleDownloadCSV} variant="outline">
                Baixar CSV
              </Button>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {collaborators.map((collaborator) => (
                  <div key={collaborator.id} className="flex items-center justify-between p-3 border rounded-lg bg-gray-50">
                    <div>
                      <p className="font-medium">{collaborator.nomeCompleto}</p>
                      <p className="text-sm text-gray-600">{collaborator.empresa} - {collaborator.cpf}</p>
                    </div>
                    <Button 
                      onClick={() => removeCollaborator(collaborator.id)}
                      variant="destructive"
                      size="sm"
                    >
                      Remover
                    </Button>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default CollaboratorFormHTML;
