import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { CalendarIcon, Plus } from 'lucide-react';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';
import { Collaborator } from '@/types/collaborator';
import { toast } from '@/hooks/use-toast';

interface CollaboratorFormProps {
  onAddCollaborator: (collaborator: Collaborator) => void;
}

const CollaboratorForm: React.FC<CollaboratorFormProps> = ({ onAddCollaborator }) => {
  const [nomeCompleto, setNomeCompleto] = useState('');
  const [cpf, setCpf] = useState('');
  const [empresa, setEmpresa] = useState('');
  const [cnpj, setCnpj] = useState('');
  const [novaEmpresa, setNovaEmpresa] = useState('');
  const [unidade, setUnidade] = useState('');
  const [grupo, setGrupo] = useState('');
  const [setor, setSetor] = useState('');
  const [gestor, setGestor] = useState('');
  const [integracao, setIntegracao] = useState<Date | null>(null);
  const [aso, setAso] = useState<Date | null>(null);
  const [nr10, setNr10] = useState<Date | null>(null);
  const [nr10Sep, setNr10Sep] = useState<Date | null>(null);
  const [nr11, setNr11] = useState<Date | null>(null);
  const [nr12, setNr12] = useState<Date | null>(null);
  const [nr18, setNr18] = useState<Date | null>(null);
  const [nr18Andaime, setNr18Andaime] = useState<Date | null>(null);
  const [nr20, setNr20] = useState<Date | null>(null);
  const [nr33, setNr33] = useState<Date | null>(null);
  const [nr35, setNr35] = useState<Date | null>(null);
  const [nr34, setNr34] = useState<Date | null>(null);
  const [pgroPcmat, setPgroPcmat] = useState<Date | null>(null);
  const [pcmso, setPcmso] = useState<Date | null>(null);
  const [ppr, setPpr] = useState<Date | null>(null);
  const [loto, setLoto] = useState<Date | null>(null);
  const [ptaPlataforma, setPtaPlataforma] = useState<Date | null>(null);

  // Novos estados para os checkboxes
  const [treinamento, setTreinamento] = useState(false);
  const [os, setOs] = useState(false);
  const [documentacao, setDocumentacao] = useState(false);
  const [aprPae, setAprPae] = useState(false);
  const [epi, setEpi] = useState(false);
  const [cipa, setCipa] = useState(false);

  const empresas = [
    'ALGAR TELECOM S.A.',
    'ALGAR TECH',
    'ALGAR SOLUCOES',
    'ALGAR AGRO',
    'ALGAR VENTURES',
    'UNA UNIVERSIDADE',
    'ALGAR MULTIMIDIA',
    'Grupo Orion',
    'SEM EMPRESA',
    'REGIA PNEUS',
    'SUPORTE INFORMATICA',
    'STERICICLE',
    'STARTEC',
    'P MAIS',
    'TOTVS',
    'Nova Empresa Engenharia',
    'cb',
    'labor suade',
    'metal frio',
    'geratec',
    'UPS SERVIÇOS',
    'automotion',
    'SO VEDAÇOES',
    'totus',
    'pcm consultoria',
    'solar',
    'interativa',
    'cernacom',
    'MOJOMIX',
    'tickt log',
    'M&M MANUTENÇÃO',
    'INSTITUTO NACIONAL DE SEGURIDADE SOCIAL',
    'amancio',
    'DNV',
    'CCIL',
    'ROSENDO TRANSPORTES',
    'eletrodata',
    'GD VIDROS',
    'VALFILM',
    'REGIA PENEUS',
    'TRANSMASO',
    'HEUFT',
    'VAZAO',
    'GERENCIAMENTO EM SEGURANÇA DO TRABALHO',
    'REAL PUBLICIDADE',
    'JG RECICLAGEM',
    'MD CERVES',
    'MEM',
    'LOW COST',
    'GC AUTOMAÇÃO',
    'QUANTICA BRASIL',
    '3 M',
    'NACIONAL TURBO DIESEL',
    'NACIONAL TURBO',
    'CENTRAL DOS ELETROS',
    'ECOLAB',
    'ATRIVIDA',
    'AGAPE',
    'TESLA',
    'VICTOR DIESEL',
    'LDB',
    'SÃO JOSÉ',
    'COLETIVO JOVEM',
    'STERICYCLE',
    'HCL',
    'SGP',
    'BGM',
    'NWN TRANSPORTE',
    'MWM TRANSPORTE',
    'MAVIL',
    'ASA BRANCA',
    'PANIFICADORA VASCONCELOS',
    'FMAGALHAES',
    'SUPERGASBRAS',
    'INTERSAFETY',
    'PRESTEX',
    'FRS',
    'GESTOR',
    'REBOQUE SAO JOSE',
    'CABO BRANCO',
    'GILOG',
    'FG CAVALCANTE',
    'DEKRA',
    'ATREVIDA',
    'NSG',
    'PROBETON',
    'METALUGICA',
    'G ORENGO',
    'COMBATE',
    'VIPAL',
    'CAGEPA CAMPANHA',
    'ELETROTRAFO',
    'REAL',
    'SAMARTIN',
    'PNEUS',
    'APVIDA',
    'ELETROCELO',
    'TRANS,DE VALORES',
    'SADA',
    'ANTON PAAR',
    'MECANEVES',
    'LOG FRIOS',
    'TRANSPORTES',
    'BRAZUL',
    'DOS MACACOS',
    'FPB',
    'NACIONAL',
    'TRANS.',
    'TAMIJU',
    'FLOUIR',
    'TRANSPORTE',
    'HAPVIDA',
    'GR S/A',
    'NIGRO',
    'CIVIL',
    'MATHEUS FEST',
    'CAMABRA',
    'SEMPRE QUIMICA',
    'SAO JOSE',
    'MOS',
    'BOREAL',
    'LOCAMERICA',
    'MERCURIO',
    'PROGRESSO',
    'ENGENHARIA',
    'NORDIFE',
    'NACIONALGÁS',
    'DIEBOLD',
    'ECE',
    'WALSERV',
    'agra',
    'ONLINE',
    'JLTC',
    'KAIZEN',
    'MASTER BOI',
    'ALVORADA',
    'EXPRESSO GONÇALVES',
    'LEÃO',
    'TETRA PAK',
    'SERVISOS',
    'MP',
    'khs',
    'SM TRANSPORTE',
    'COREMAL',
    'BRG',
    'ministerio do trabalho',
    'COOP',
    'CENTRO AR',
    'ESTAF EQUIPAMENTOS',
    'ENERGISA',
    'PROTEMAXI SEGURANÇA',
    'BOM',
    'hexis',
    'emerson luiz dos santos',
    'UPTON',
    'BALL',
    'VG TECH',
    'NORSA CABO DE SANTO AGOSTINHO',
    'SUPERGABRAS',
    'merck',
    'protec',
    'selva',
    'ABB',
    'CORREIA E PEIXOTO',
    'tetra pak1',
    'UNIVERSAL',
    'coopergas',
    'CONTRUMAIS',
    'HNR',
    'QUALINTER',
    'uptonerfg',
    'pcmwdfe',
    'ELETROTAFO',
    'itep',
    'ASSUNÇÃO',
    'TAYTAMIJU',
    'HEINEKEN',
    'MANGABEIRA',
    'MATERIAIS',
    'TRANSPRTE',
    'TERMO BEM',
    'TETRA PACK',
    'TECNOLOGIA',
    'SOLAR CAF',
    'CRISTAL PET',
    'khsk',
    'PB AMBIENTAL',
    'METAL PRATICO',
    'MAQ ENGENHARIA',
    'FONTANELA',
    'CSI',
    'KM',
    'LOCAR',
    'TRICS LOG',
    'LIQUIDE',
    'RCW',
    'samatec',
    'lgv',
    'KEIJO',
    'CENTRAL ORTE FRUTAS',
    'cms',
    'BAUKO',
    'GRAFICA JB',
    'TERMACO',
    'domino',
    'IBS',
    'SINDCATO',
    'ADS',
    'JS TRUCK',
    'COMPET',
    'SUPER BID LEILOES',
    'VIDIOJET',
    'MIRVI',
    'PRISMATUR',
    'WHITE MARTINS',
    'DEEC OTICA',
    'ATLAS',
    'CELIO TRANSPORTE',
    'CELPE',
    'ASTECENDIO',
    'PROXXI',
    'PRESTETEC',
    'EXATA CARGO',
    'GE WATER',
    'ANJ',
    'ICETOS',
    'protege-sms',
    'SOLAR ESCRITÓRIO CENTRAL',
    'KARNE E KEIJO',
    'MC PACK',
    'velog',
    'ELOS',
    'TECLABOR',
    'MOTIVAR',
    'CHN',
    'SPIRAX SARCO',
    'NOVA ERA TRANSPORTE',
    'NOVA ERA TRANSPORTES',
    'PRESS',
    'ALPINISMO',
    'PROTELE ENGENHARIA',
    'PROTEGE',
    'INDUSTRIA REUNIDAS RENDA S.A',
    'ENGENHAR',
    'servis',
    'BRF S.A',
    'SENAI PERNAMBUCO',
    'VALMASTER',
    'antopar',
    'RMS INDUSTRIALTECNICA',
    'BRASIL GAS',
    'FLUE',
    'GUINCHOS',
    'SMART  CONSULTORIA',
    'NOVAL',
    'BIO AGRE',
    'BMS',
    'JR',
    'bens',
    'BETON',
    'DOM',
    'cagece',
    'correrecnica',
    'TEKNOL',
    'GASBRASS',
    'FESTE',
    'LIDER TELECOM',
    'souza e marcedo',
    'P.CIVIL',
    'LINCON',
    'MACRO',
    'MR BOMBAS E MOTORES',
    'PETROBRAS',
    'FERMAC',
    'microtec',
    'sc correntes',
    'PROX',
    'SEGURANÇA',
    'tranportes',
    'PROTECTA',
    'gocil seguranca',
    'SOLARIS',
    'corremaq',
    'FIMAP',
    'montcal',
    'orcan',
    'CONSTUMAS',
    'RODOBENS',
    'rgis',
    'VERTICAL',
    'CETIS',
    'TRANS',
    'PERFIL',
    'ifl',
    'TARZAN',
    'BONFIM',
    'MONTEC',
    'RECUPERADORA',
    'ROULD',
    'BICH BLINTS',
    'pm',
    'Cross Santa Cruz',
    'NS Brazil Revestimentos Especiais',
    'LIESS',
    'GENESIS',
    'MC REPRESENTAÇÕES',
    'RM',
    'BATISTI',
    'CASA DA MOEDA DO BRASIL',
    'EWE CONSULTORIA E INSPEÇÃO',
    'vip encomendas',
    'gerentec',
    'VASF',
    'REDE CONECTA',
    'GRANBEL',
    'KAEL DISTRIBUIDORA',
    'AROL',
    'BRF',
    'RODOBANC',
    'policia',
    'METALFRIO',
    'WORK TECH',
    'BELT',
    'TRIXLOG',
    'BEX',
    'LINQ',
    'STARTUP',
    'NETZSCH',
    'MULTIPLOS',
    'sipa',
    'E2PS',
    'UNIS',
    'PK',
    'PINTEMAR',
    'ALFA',
    'CISVIVER',
    'hd transportes',
    'IBL',
    'BOA VIAGEM',
    'ETECH COMPRESSORES',
    'MS',
    'AL',
    'BRADESCO',
    'CONVERGE',
    'AK',
    'LF',
    'LOG FRIO',
    'RGL',
    'USIMAR',
    'DOTO',
    'MADIS',
    'SEW',
    'SCHAFER',
    'L AMORIM',
    'DALL AGNOL',
    'ARTES',
    'LAMORIM',
    'FAZ PROMO',
    'TOPRINT',
    'CEFOR',
    'A',
    'RB',
    'GILSON MEDEIROS',
    'USIANA OLHO DAGUA',
    'COMAPRO',
    'RENOL SERVICE',
    'AGOGOL',
    'GOLGOL',
    'MAC ENGENHARIA',
    'RAWTEC',
    'FRIO',
    'VICTORDISEL',
    'AVANTE',
    'HIDROSONDA',
    'PS TRANSPORTE',
    'ECORPLAST',
    'CARBO GAS',
    'CIANO SOLUÇOES AMBIENTAIS',
    'VAL',
    'valfilme',
    'IMAGEN',
    'NACIONAL GÁS',
    'TECHNOFRIO',
    'SEGURADORA',
    'MNS METALURGICA',
    'SPRI',
    'LUMINS',
    'sl solar',
    'PAU BRASIL',
    'RIO DO PEIXE',
    'VVC',
    'RAPIDÃO BR',
    'TRANSBONO',
    'IBNOX',
    'PERICIA',
    'FIEMA',
    'PROTECMA',
    'ANTONIO MOTOS',
    'TOLEDO',
    'DMARI',
    'PPQ',
    'NOE LOGISTICA',
    'bom pão',
    'arame',
    'cvm',
    'GDM',
    'COBESA',
    'BATIST',
    'SÓ MOTORES',
    'gs mangueiras',
    'PATIO NORTE',
    'MENTAL MONTE',
    'GALVAO',
    'JAD EXPRESS',
    'TERA TELECOM',
    'GBLEX',
    'LINEAR',
    'nos controle',
    'LUARTE',
    'MAC FACILITEIS',
    'galpão de ideiaa',
    'BUFFET BOM DEMAIS',
    'amc do brasil',
    'SERCOS',
    'SIK',
    'FERGE',
    'Empresa testeF',
    'JA',
    'MADSERVES',
    'CALDADO TRANSPORTE',
    'JC DECALTES',
    'DOUTOR BATERIA',
    'bombeiro',
    'radiotech',
    'MENDES PINTO',
    'AHT',
    'CHIAVERINI',
    'universal transporte',
    'grande trabalho sim',
    'PNEU CENTER',
    'revitaliza eng',
    'strada',
    'prodeg auditoria',
    'PB GAS',
    'D LASER',
    'HAVAINA',
    'TQS',
    'RUENSE',
    'sidicato',
    'BOSCH',
    'IMPERIO SERANO',
    'COZITEC',
    'faisca soluções',
    'T',
    'TAO',
    'SEMEQ',
    'installer',
    'DISTRIBUIDORA MEDEIROS',
    'MADISA',
    'QUALITY',
    'AEGIS',
    'RA SOLUÇÕES INDUSTRIAIS',
    'SANTO AGOSTINHO',
    'MOVELOG',
    'comptec',
    'JT',
    'BELA FESTA',
    'Despoluir',
    'york',
    'CERRADO',
    'JS DA PENHA',
    'CMV DO MEARIM',
    'EMPRESA1',
    'ALUGUE',
    'alupe',
    'teste visão',
    'alupe teste',
    'FARADAY',
    'logistica',
    'SOMOV',
    'GIL MOTO',
    'ATC',
    'TRANSBRAGA',
    'ICP',
    'THT',
    'PB',
    'sm adesivagem',
    'FGENES',
    'perto',
    'super gas',
    'PISOS',
    'TECLOBAR',
    'HYTORC',
    'LCB',
    'LATAN',
    'ALFEX',
    'OFIMEC',
    'LL-ENGENHARIA',
    'ambito',
    'JA METALURGICA',
    'CONCRETOS',
    'PROJECTA',
    'heiniken',
    'PMAIS',
    'GTECK',
    'OLIVEIRA',
    'aço brasil',
    'WR TRANSPORTE',
    'REBOQUE',
    'FAM',
    'OI',
    'grupo sucesso',
    'VIEW',
    'FLUENCE',
    'exactcontrou',
    'LOGFRIO',
    'C.V DO MEARIM',
    'hap vida',
    'TEC TUBE',
    'R LUZ',
    'positronic',
    'SA CAVALCANTE',
    'ferreira serviço',
    'METALMA',
    'SADA TRANSPORTE',
    'PRODELOG',
    'METRO',
    'phocus',
    'I NOVA',
    'service',
    'COPA EXITO',
    'EMVIPOL',
    'HG',
    'TECNOMAN',
    'VIGILANCIA SANITARIA',
    'CROWN',
    'unidas',
    'montagem',
    'SESI',
    'samed',
    'REFPALET',
    'dds',
    'instituto maranhense',
    'somas',
    'LIMPA FOSSA PARNAMIRIM',
    'JORNAL AGORA',
    'CHAVEIRO',
    'uranus',
    'AUTODRO',
    'AUT SERVIÇE',
    'TECALTO',
    'VEPREL',
    'trt',
    'URBE PROJETOS E CONSTRUÇÕES',
    'ARY GUINCHO',
    'DATA PROMO',
    'MAC FACILIS',
    'DE DAVI',
    'OJB TRAGOGRAFO',
    'PONTO DIGITAL',
    'flex',
    'DATA PROM',
    'TECNOMAM',
    'CLAND',
    '2.G',
    'PB AVERLINO',
    'VALSERV',
    'SOLUÇOES',
    'PRODEG',
    'MJS TRANSPORTES',
    'MJS',
    'MARTINS',
    'CHAMATEX',
    'RAPIDOBR',
    'DIVERSAY',
    'sadia',
    'tres corações',
    'maquinox',
    'CAVALCANTE ARQUITETURA',
    'multifrutas',
    'jma',
    'CAMPINENSE',
    'vipetro',
    'CEPA',
    'MILLS',
    'SÁ CAVALCANTE',
    'gold shopping',
    'TRANSNET',
    'seleção',
    'candidato',
    'agroquimica',
    'UNIGRAF',
    'compal',
    'fenix',
    'supergas',
    'distribuidor de peças',
    'krones',
    'Qualinte',
    'BRASEV',
    'canpack',
    'casa do menor trabalhador',
    'BRASECO',
    'NC  TRANSPORTE',
    'TECNOFRIL',
    'SSO RESGATE',
    'forbb',
    'video jet',
    'PLANUS INF',
    'DXD ENGEN',
    'MObil',
    'ASTRAL',
    'SUPER GÁS BRAS',
    'MIDIA DIGITAL',
    'KJP',
    'protemaxi',
    'SUBSOIL',
    'TCM EXPRESS',
    'LARIFO',
    'mosaico',
    'A e B MUDANÇAS',
    'GS CAVALCANTE',
    'FeJ POÇOS',
    'dararu vidros',
    'FLUIR',
    'CAEL',
    'MSLOG',
    'LEAL VASCONCELOS',
    'SUS',
    'MOTO LINK',
    'STOMPO',
    'ELOG',
    'LC CLIMATIZAÇÃO',
    'algas',
    'PAULO MELO',
    'moloke',
    'POTENCIAL ENGENHARIA',
    'ENTREVISTA',
    'unimetais',
    'TEC-HIDRO',
    'OTORTEC',
    'wso',
    'conceito',
    'ARPLAN',
    'CLIMATEC',
    'DUBICO',
    'TOPLINE',
    'MONTE FORTE',
    'SINE-PI',
    'RAVI',
    'CRIL',
    'MS LOG',
    'CONS',
    'TOP MANUTENÇÃO',
    'QMC',
    'cons. amacio',
    'EMPACK',
    'leite cem',
    'MAKE',
    'AMACIO',
    'SMS',
    'BIOAGRI',
    'LOWCOSP',
    'ciee',
    'MAREL',
    'NA ENTULHO',
    'visar transportes',
    'FEDEX',
    'PLANOS',
    'MAYKAWA',
    'MATEUS',
    'GRSA',
    'tigro',
    'AZUL CARGO',
    'SERGIO MATERIAL DE CONSTRUÇÃO',
    'macropack',
    'RR REFRI',
    'BELAS FESTAS',
    'Eespaço Virtual',
    'INOVER',
    'ades',
    'inmetro',
    'mestre sala',
    'RB TRANSPORTES',
    'AGUAS DE TERESINA',
    'X TEC',
    'EBENEZER',
    'ALTO MOLAS PROGUESSO',
    'HSE',
    'GLOBAL CARGO',
    'SAMAR',
    'ASSIS',
    'RANDON',
    'destaque reveste',
    'doce quitanda',
    'FESTO',
    'AVEX',
    'NORDEX LOG',
    'MAC-Q',
    'BR REBOQUE',
    'LIMA CANDEIA',
    'TELAPORTE',
    'DENVER',
    'MEW. BRASIL',
    'IOSTAQUIO',
    'ENGESERVE',
    'JUNIOR DECLARAÇÕES',
    'AEROPORTO ALUIZIO A.',
    'THIAGO FESTA',
    'PROBRETON',
    'ecotec',
    'LAUDEX',
    'ENLUR',
    'RESGATE',
    'FENIX MOVEIS',
    'MD',
    'UNISYS',
    'pb-ambiental',
    'A GERADORA',
    'ARCKMIRANDA',
    'rodoviario nordestino',
    'TRISLOG',
    'MV CONSTRUTORA',
    'CASA E COR',
    'MOTO EXPRESS',
    'BECKMAN',
    'ANALDO REBOQUES',
    'FOURFLEX',
    'NSI',
    'ORTOTEC',
    'KOMATEC',
    'consultoria',
    'MONSTER',
    'BRASIL GÁS',
    'VAL MÓVEIS',
    'MATINCETIS',
    'PARKMATIC',
    'New empresa',
    'nova empresa',
    'empresa teste 01',
    'ESFERA',
    'LÍDER TELECON',
    'FAVELA DO SAMBA',
    'TRANSPANTANAL',
    'LL ENGENHARIA',
    'ANTONIO OVO',
    'coca-cola brasil',
    'agogo',
    'FESTA DE BALAO',
    'ageradora',
    'BRASPRES',
    'KURIOS',
    'C3 ENGENHARIA',
    'TOPPER',
    'rtr',
    'auxTeste',
    'BRASUL',
    'COMATEC',
    'Clinepipe',
    'HC',
    'EMBRATEL',
    'QUALITAL',
    'ARAUJO ABREU',
    'EXPRESS TCM',
    'khs Indústria de Máquinas LTDA',
    'sonata',
    'LIMA TRANSPORTE',
    'REBOQUE SÃO JOSÉ',
    'Metal truck',
    'Tolledo',
    'RS TRANSPORTES',
    'ANTÔNIO OVOS',
    'md teste',
    'PURELENS',
    'NBS',
    'JAEL MAQ',
    'nasa',
    'DANFUSS',
    'Petrobrás',
    'VOTORANTIM',
    'VISAR',
    'tay tamiju',
    'TELEMACK',
    'MARAJÁ',
    'casa do construtor',
    'restec',
    'MAXSLG',
    'jato vidro',
    'ABC INCÊNDIO',
    'AD GASES',
    'UNIÃO PAULISTA',
    'GBEX',
    'SETE ENGENHARIA',
    'COMPANHIA PB DE TEATRO',
    'DWA ENGENHARIA',
    'DTW ENGENHARIA',
    'USITEC',
    'LOCKCENTER',
    'BR LOGISTICA',
    'TECLABO',
    'Polypack',
    'LIMNOS',
    'OLIVEIRA LOGISTICA',
    'COMPETEC',
    'CREA MA',
    'TOC RETOQUE TINTAS',
    'GARANTIA REAL',
    'ccl',
    'GRUPO SIMÕES',
    'AIR SEMEAR',
    'ROBERTO TRINDADE GRAVAÇÕES',
    'BUS TRANSPORTES',
    'FISIOQUALI',
    'RCR',
    'MAPE TRANSPORTES',
    'TRANBRAGA',
    'TITARA',
    'GTP',
    'CONSELHO DE ENERGIA NUCLEAR',
    'MONTETUDO',
    'RAPIDÃO COMETA',
    'TECSUL',
    'POSITIVA SERV. INDUST',
    'LRC COMERCIO LTDA',
    'PUBLICO FEDERAL',
    'EMAPLA',
    'almeida junior',
    'METALURGICA',
    'gps',
    'CARNES',
    'FUCHS',
    'SD engenharia',
    'ALIMENTOS',
    'RECIFER',
    'MARELLI',
    'GEANE GALVAO',
    'DESIGNER BRASIL',
    'ESCAPE HOUSE',
    'DUDU MATERIAL',
    'SaS turbo',
    'dsr',
    'abcdert',
    'FACULDADE PITAGORAS',
    'TRAMONTINA',
    'PLURAL',
    'PACK',
    'UNP',
    'PROARDI',
    'BEM AMIGO',
    'RANDSTAD',
    'Natal Telecom',
    'GBTecnica',
    'INTERTEC',
    'DIR PRODUCAO',
    'MARY KEY',
    'LOJA DAS CORRENTES',
    'MC TRANSPORTES',
    'ar',
    'IDEMA',
    'AMBIENTAL',
    'CONTROLE TECNICO',
    'VASCONCELOS EVENTOS',
    'aguiar eng',
    'MOURA',
    'MCN TELECON',
    'HANDSTARD',
    'PALETRANS',
    'TRANS. EPOCA',
    'MOOVE ENERGIA',
    'EZICOM',
    'SENASTEC',
    'GRANITUS',
    'CONSTRUÇÕES',
    'INST. FLORENCE',
    'OdontoPrimus',
    'EMBERA',
    'CHRONUS',
    'MANJA',
    'RODO CARGAS',
    'ERNEST',
    'MEDEIROS',
    'MC Motos',
    'BRINQUEDOS E BRINCADEIRAS',
    'ECOLABE',
    'Engenharia e Serviços',
    'BACABAL REFRIGERACAO',
    'Manutenção e consultoria',
    'Metal Mecanica',
    'Automação',
    'EXCELLENCE',
    'PLASTICOS NOVEL',
    'projetos',
    'POLIPACK',
    'MANUTENÇÃO',
    'PESAGEM',
    'BIOTECS ENGENHARIA',
    'VIDRAÇARIA',
    'G A GUINDASTE',
    'Embalagens',
    'Auditor',
    'solucoes ambientais',
    'Nutri',
    'QUIMITEC',
    'COLETA',
    'Equipamentos',
    'ZAPE',
    'LOCDECORE',
    'informatica',
    'IMPRESSORAS E CIA',
    'SCOLLT',
    'RN JUNIOR',
    'LOGUINTE',
    'Bombas',
    'FLOREST',
    'MPN',
    'LOPESTEC',
    'DIVERGENTE',
    'ELINQ',
    'JOBTECH',
    'g trigueiro',
    'ROLIMEC',
    'Fonte da Vida',
    'CENARCOM',
    'VENTARE',
    'VIDRAÇARIA ALUMINIO E CIA',
    '1 LUZ EVENTOS',
    'ZCOM',
    'GRAFICA',
    'Peças',
    'comaf',
    'FMAGALHÃES',
    'REDUX',
    'MUNDO DO VIDRO',
    'ART',
    'NS BRASIL',
    'CT GAS',
    'proteção visual',
    'FOCA CARGA',
    'PROCESS',
    'FILTEC',
    'MIAKI',
    'Artigos para Laboratórios',
    'ELETROCLIMA',
    'RCM ENGENHARIA',
    'hp',
    'CARNEIRO',
    'DELL',
    'SIPA',
    'ENTULHO POTIGUAR',
    'CAERN',
    'EXTINTORES',
    'REFRIGERAÇÃO',
    'LOPES TEK',
    'Tecnoiso',
    'ES MONTAGEM',
    'BMD',
    'comtrasil',
    'SOFERRO',
    'MAPROS',
    'JUNGHEINRICH',
    'BLOCO',
    'SINDBEB',
    'SERVSEC',
    'KUKA ROBOTER',
    'Mirante',
    'SHERWILLAMS',
    'tecno',
    'conserv',
    'LK LOGISTICA',
    'DEVICE',
    'AIS INSPEÇÃO',
    'BGM ALIMENTOS',
    'SANMARTIN',
    'SÃO JOÃO',
    'BM SONDAS',
    'SERVI CONSULTORIA',
    'PRONTOSERV',
    'SEG',
    'BURGMANN',
    'tec',
    'segvieg',
    'AILERT',
    'AIR LAB',
    'sindi',
    'BR',
    'DACAR',
    'radio',
    'DUAL TEC',
    'TRANSFORTECH',
    'REOPEM',
    'Danfoss',
    'CRISTAL ENGENHARIA',
    'ORDEM DOS ADVOGADOS DO BRASIL',
    'Filho',
    'GELA NORDESTE',
    'PRINT',
    'Ge',
    'Esmaltec',
    'PORTO SEGURO',
    'grupo brasmo',
    'Interativa Empreendimentos e Servicos de Limpeza e Construcoes LTDA',
    'GRANDE',
    'trix',
    'open',
    'PONTUAL SERVIÇOS',
    'Forbo',
    'AGRUPAR',
    'NORDESTE',
    'de vida',
    'FUNCIONAL',
    'PAKMATIC',
    'Federal',
    'OMNITRADE',
    'CONSELHO REGIONAL DE QUIMICA',
    'GHS',
    'SSMA',
    'lipesa',
    'nox',
    'técnica',
    'M DIAS BRANCO',
    'ANDESUS',
    'EFICIENTE',
    'Lubrisirt',
    'clinica ceda',
    'WMS',
    'PALL',
    'eketro',
    'sigma',
    'COMERCIOS E SEVIÇOS',
    'JAMEF - TRANSPORTES',
    'CUTELARIA BR',
    'HENKEL',
    'TRUCK',
    'COMERCIO DE MAQUINAS',
    'IDEIAS',
    'Correios',
    'Crion',
    'DUAL',
    'PXX',
    'PROSEGUR',
    'PKG Brasil',
    'MIX',
    'SANTANA',
    'refrisul',
    'WINSPECT',
    'empredimemntos',
    'Gale',
    'ENERGY',
    'CONSELHO FEDERAL DE QUÍMICA',
    'DIAS',
    'ZELA',
    'JR ARAUJO',
    'GF',
    'KYU',
    'Epo Montagem',
    'INDUST. CIMENTO',
    'CARNE QEIJO',
    'PAO DOCE MEL',
    'ASSECH',
    'AGUA VIDDA',
    'SEGIVEW',
    'LEGUMES E CIA',
    'Kay',
    'motores',
    'manutec',
    'ASSECORIA E TREINAMENTO',
    '_',
    'Santos',
    'Promo',
    'FM MOTOS',
    'SOLITICAS',
    'SOLISTICA',
    'OVOS',
    'VACCINE',
    'Brasil',
    'BUREAU',
    'visita',
    'ART FRUTAS',
    'industria e comercio ssa',
    'trasnportes',
    'autentica',
    'MERCEDES',
    'FESTAS',
    'GÁS BRAS',
    'MATEC INFOR',
    'VASCONCELOS',
    'PRESERV',
    'EQUIPAR',
    'segseguro',
    'Constutura',
    'vida',
    'CMC',
    'visitante',
    'MASTERBOI',
    'unilare',
    'desart',
    '5A',
    'PREVENÇÃO',
    'tech',
    'Boticario',
    'sousa log',
    'LEGUMES & CIA',
    'LOG',
    'MYNASRKI',
    'MOSAIC',
    'fs logistica',
    'TRANS VICTOR',
    'TRANSGESP',
    'SEMEAR',
    'PEIXOTO',
    'one wey',
    'COSTA ENGENHARIA',
    'ARCAM',
    'EMPLACAMENTO',
    'GB BEX',
    'CLINICAS DAS CADEIRAS',
    'JOCARTS',
    'SÓMANGUEIRAS',
    'transportadora',
    'geoser serviços geológicos',
    'PB GÁS',
    'MELHORAMENTOS',
    'JOHNSON CONTROLS',
    'OMRON',
    'VALMETAL',
    'SMC',
    'FM2C',
    'siemens',
    'VMC TRANSPORTES',
    'CRN',
    'DECRA',
    'servimateltda',
    'MEGA NORDESTE',
    'OPÇÃO',
    'ALPUNTO',
    'watts led',
    'Guarnieri Engenharia',
    'MTECH',
    'SARCO',
    'RECIFE COMERCIO',
    'sindicato',
    'DELTA CONTAINERS',
    'karnekeijo',
    'endress+houser',
    'TN TRANPORTE',
    'ALBERSON B FOTOGRAFIA',
    'fribal',
    'PANIFICADORA VASCOLCELOS',
    'MAGNABEL',
    'REVIBRAS',
    'ATEC MANUNTEÇÃO EMP.',
    'PAVEL',
    'edj poda',
    'MARQSERVICE',
    'AEROLIM',
    'NORDESTE MANUTENÇÃO',
    'MOB TELECON',
    'TCNO FRIO',
    'FORTAL AUTOMAÇÃO',
    'EMERSON',
    'BOM LEITE',
    'EMGEARRIA CORREA PEXOTO',
    'PBGAS',
    'LOCAÇÕES',
    'SINALIZE',
    'SHERATON',
    'gsm gráfica',
    'EMITTER',
    'brasilgas',
    'LOOP BRASIL',
    'AUTO',
    'QUIMICOS',
    'MAR SERVICE',
    'CORRENTES',
    'HORAND',
    'Previne',
    'NORTE',
    'VIA LINPA',
    'FAZMAN',
    'EMPLACADORA',
    'mc enventos',
    'TERMICA',
    'exbras engenharia de insendio',
    'SELEÇAO MUNDO SERVIÇOS',
    'G1000',
    'RE',
    'SEMPRE QUÍMICA',
    'VECHEL',
    'Life',
    'GEISEL',
    'JPINTO',
    'BRS',
    'AUDITORIA',
    'ROOTER',
    'ISMA',
    'DELMAR',
    'CALIBRAÇÕES',
    'TECMAR',
    'INJETROTEC',
    'comunicação visual',
    'FORTE',
    'ROLTEX',
    'NORTE SOLUCO',
    'ANDRADE',
    'CIMCORP',
    'PERTO CATRACA',
    'LIRA',
    'Sistemac',
    'PREDMEC',
    'OTTIMA',
    'CHAPOS',
    'INTERATIVA EMPREENDIMENTOS',
    'thay festas',
    'BIFE NEO ANTUNES',
    'unibra faculdade',
    'MOTOSHOCK',
    'perteci',
    'NKA',
    'ANDALUZ',
    'TRIX  log',
    'BDG',
    'CARGO',
    'CAPACITAR',
    'REAL SEGURAÇA',
    'KAPO',
    'transvicon',
    'MOLDINTEC',
    'focus',
    'CHUVA DE IDEIA',
    'POTIGÁS',
    'COLLTHECH',
    'ENG',
    'exis',
    'BANDEIRANTES',
    'idustrial',
    'MIX SERVIÇOS',
    'Integração',
    'LOGMAN',
    'FARRAPOS',
    'MONTAN',
    'gren maia',
    'log log',
    'KLINGER',
    'ENCEETEL',
    'ONE',
    'DREAM',
    'cap',
    'Policlinica',
    'FLUIDCOM',
    'PIZANI',
    'ALEX REBOQUE',
    'EDS ENGENHARIA',
    'planus informatica',
    'SE//EQ',
    'EMLUR',
    'ULLTRALIMPO',
    'JAV',
    'CLEANSTORE',
    'CLINSTORE',
    'REMAX',
    'lugger brasil',
    'SISTEMAS',
    'INDUSTRIAL',
    'CONECTA',
    'CEMAR',
    'ROLIMÃO',
    'WMC REFRIGERAÇÃO',
    'ROMATEC',
    'ARCANT',
    'VIDRAÇARIA ALUMONIO E CIA',
    'BRASRENTEL',
    'FATO PRODUÇÃO',
    'vertical empilhadeira',
    'CARCHER',
    'SDCAR',
    'VIDROS',
    'EDILSON',
    'ZUTINI',
    'ISPE',
    'ANDRADE ANDRADE',
    'hipertec',
    'AIRLAB',
    'P7',
    'AMDINIZ',
    'CAVALCANTI',
    'arqueitetura',
    'topos informatica',
    'KARCHER',
    'Primax',
    'AERO MILE',
    'SOLUÇÕES INDUSTRIAIS',
    'FANNIX',
    'GERADORES',
    'COOLTECH',
    'gestaão patrimonial',
    'pack pack',
    'Recbras',
    'FILMAGEM',
    'BOI',
    'endress',
    'PACKTEC',
    'LAC',
    'SYNTAGMA',
    'ifm eletronic',
    'DISCK TRANS',
    'BLOCOS',
    'PORAQUE',
    'EMBASA',
    'MIGUEL VERJOS',
    'MKALL',
    'krs',
    'MS MANUTENÇAO',
    'METAL MONTE',
    'Inema',
    'MUNCK',
    'LM ENGE',
    'MULTIGÁS',
    'SERRAE COMPANY',
    'POLO ENGENHARIA',
    'previ',
    'FESTIVAL HALELUIA',
    'LABORATORIO LEME',
    'MONTAGENS',
    'municipal sms',
    'NM MOTA REFRIGERAÇAO',
    'É BOM',
    'Mauricio de Nassau',
    'NORDESTE SHP',
    'LATINA',
    'ENGECON',
    'UNIVERSOS',
    'produçoes',
    'TEAM',
    'Net',
    'Nordeste Lubrificantes',
    'ADMICIONAL',
    'CPCON',
    'Solares',
    'TRANSPORTES.',
    'SENSORS AND INSTRUMENTS',
    'CARDAN - NORDESTE',
    'FERG',
    'NK TONEM',
    'AMERICATAMPAS',
    'FAMA',
    'REMOTA',
    'RP',
    'EY',
    'DO BRASIL',
    'SLZ TRANSPORTES',
    'AGUA VIDA',
    'DASART',
    'FC ENGENHARIA',
    'mc',
    'GUEDES TRANSPORTES',
    'labor life',
    'POLI ENGENHARIA',
    'REDE SUPER LEGAL',
    'vistorias',
    'TOTTI EQUIPAMENTOS',
    'TRANSPORTE LOGÍSTICA',
    'ENGENH',
    'MAQUINAS',
    'Gympass',
    'CASA DA MOEDA',
    'merylux',
    'MAN',
    'MEZA ENGENHARIA',
    'NDL',
    'IESP',
    'CASTROSUL',
    'DINAMI',
    'VR  TRANSPORTES',
    'RBR',
    'ARB ENGENHARIA',
    'nove',
    'ALFINIR',
    'RENAUX',
    'ARQUITETURA',
    'JRM',
    'ART LUX',
    'SABARA  QUIMICOS',
    'MARAVILHA MOTOS',
    'fultec',
    'mpt',
    'DCL TRANSPORTE',
    'SOLUÇÃO EM GASES',
    'vagalume eletrico',
    'SEMEC',
    'TERRA',
    'SAUTER',
    'MARQUIZA EVENTOS',
    'TERRABRASIL',
    'SUSTENTABILIDADE',
    'ASSEGH',
    'PERNAMBUCO DISTRIBUIDORA',
    'CRTV',
    'MOTOCAR',
    'tec frio',
    'MUNDIAL LOGISTICAS',
    'BRIM',
    'MADRI EXPRESS',
    'ALEM DO PÃO',
    'MENDES',
    'BLOCK CONSTRUÇÕES',
    'APREVEM CONSULTORIA',
    'coopersucar',
    'SEGURADORA TRANS',
    'AZ - CONSTRUÇÕES',
    'MOVEIS',
    'POSSTAL-LOG',
    'SUDAM',
    'PROXI',
    'AQUAPRO',
    'PRO-LOG',
    'supermix',
    'BORA TRANS',
    'RLTRANSPORTE',
    'COMERCIO',
    'REDE FEMININA',
    'CONSULTORIA SHS',
    'REIS',
    'pallet',
    'termix',
    'RS CAR',
    'antonpa',
    'ecolabi',
    'CSM',
    'SINDICATO DOS BUGGUEIROS',
    'SUPORTE ONIMITRADE',
    'sao jose pinheiro',
    'bahia',
    'MAGNA - LOCAÇÕES',
    'ASSISTERMARCO',
    'MOTOS',
    'ACRILPLAC',
    'RITA',
    'simoes filho',
    'FONTEK SERVIÇOS',
    'ITADUR',
    'BOMBEIRO MILITAR',
    'M.S LOGISTICA',
    'ERNEST YOUNG',
    'ALPHA',
    'EXPRESSOTEC',
    'ARATES',
    'siatemas',
    'TELECOM',
    'PRECISO',
    'JB  TRANSPORTES',
    'CONSULT',
    'luiz',
    'COMELO ENGENHARIA',
    'HOLANDA REFRIGERÇÃO',
    'HERMONT',
    'DRIVEMAX',
    'aertec',
    'Estrategic',
    'engenha',
    'SAGA-TRASPORTES',
    'ALVORADA MOTO',
    'babaçu',
    'correntes cobra',
    'KMJ PRODUÇÕES',
    'AL SOLUÇÕES',
    'ASPEC.ENG.',
    'MA',
    'FETRAMAG',
    'SERVBRASIL',
    'AFC',
    'CENTRAL CAR',
    'AMBREOE',
    'GOOD SERVICE',
    'STEEL',
    'MARSH',
    'ENGEN',
    'AGÊNCIA ESTADUAL DE MEIO AMBIENTE',
    'MCI',
    'S.BUILD',
    'cac-projetos',
    'SBS OUTDOOR',
    '2AP ENGENHARIA',
    '2A',
    'TCMS BRASIL',
    'SEMOB',
    'backman',
    'DACUNHA',
    'OXISOLDAS',
    'SIDEL',
    'ATLAS COOP',
    'MONTERCAL',
    'VJ - AUTOMAÇÃO',
    'NETSZCH',
    'GETRK',
    'INNOVA',
    'BESTPLACE',
    'NCH',
    'MECVED',
    'PAVAX',
    'TORYKS',
    'WJP',
    'SOUZA RANGEL ISOLAMENTOS',
    'TRANSP',
    'ABC COMPRESSORES',
    'INT',
    'CARGA',
    'nova forma',
    'TESLATEC',
    'JANSERV',
    'Metallub',
    'AUTROM - AUTOMAÇÃO',
    'KMTEC',
    'Monta',
    'fellws',
    'MFARTEFATOS',
    'SERILON',
    'GLOBAL',
    'COMPESA',
    'SYSTEM PLASTIL',
    'ALFA OMEGA',
    'JM SERVIÇOES LTDA',
    'KSB',
    'NKA TONER',
    'AQUALUX',
    'REFRAICOL',
    'JR PNEUS',
    'CEPTIS',
    'SHERWIN WILLIANS',
    'GUS DA FESTA',
    'DOT',
    'IDEIA',
    'ABAITI SERVIÇOS',
    'PREDIMEC',
    'SUDIC',
    'IDENTIFICK',
    'RC REFRIGERACAO',
    'MAXSEG',
    'SUAPE ROLAMENTOS',
    'SACMI SACMI',
    'TERUEL',
    'A. Empilhadeira',
    'USIMAN',
    'SOMA TEC',
    'NORDEMEL- HIDROELETRICA',
    'AÇO MA',
    'VP MOTO',
    'DOS PARAFUSOS',
    'RICCO - ALIMENTOS',
    'MCDONALDS',
    'NCR',
    'IRON',
    'LM-CAP',
    'EQUIP',
    'COBEPAL',
    'BEM ESTAR',
    'PSIU INDUSTRIA DE BEBIDAS',
    'TRIX LOG',
    'COINF',
    'MARTIN CIENTIFICA',
    'NORTEL',
    'FRIO PEÇAS',
    'Banner',
    'BRASPRESS',
    'EMAP',
    'G.E Construções e Serviços',
    'BALASKA',
    'VIVER BEM',
    'KARNE KEIJO',
    'TRANSPOR',
    'CITRUS JUICE',
    'SUAPE',
    'COLOSING',
    '3 G. ENGENHARIA',
    'GR/SA',
    'MERCOL',
    'PEF COMERCIO',
    'ASPILL',
    'RODO TRANSPORTES',
    'Eletroflash',
    'ENVASE BR',
    'ELETROVASF',
    'PERFILGRAF',
    'GRANJA ACAI',
    'SoftwareOne.',
    'SHALON REFRIGERAÇÃO',
    'LANCER',
    'DIST - ASSIS',
    'NORDESTE ROLAMENTOS',
    'REALCEMA PLASTICOS',
    'LV TELECON',
    'EMPRESA MAPIAR',
    'LUGER BRASIL',
    'MEGA PEDRAS',
    'Green 4T',
    'TDR ISOLAMENTO E REF.',
    'C. VASQUES',
    'DE PALCO',
    'MM-PLANEJADOS',
    'VIDEO SOFT',
    'CEMEC',
    'EDIS-PRODUÇÕES',
    'Q.A.I. ENGENHARIA',
    'POLI DISEL',
    'EXPRESSO TEC',
    'JY REFEGERAÇÕES',
    'BRASMO',
    'URANOS- EXPRESSO GRAFICA',
    'HAZTEC',
    'ANJELOS',
    'INVERSORES AMERICANA',
    'TAGEM',
    'COMMANDERES',
    'EMPERSOL',
    'MOTIR-ON',
    'GOODYEAR',
    'ITEC',
    'ANGELI',
    'TOP LIMP',
    'MIDIA DIG',
    'ELDER FABIANO',
    'HOME CENTER',
    'JR LOCADORA',
    'SOS',
    'RBS CONTRUÇÕES CIVIS',
    'ESTOFADOS RIBEIRO',
    'JARDINAGEM',
    'COMAPRO AUTOMAÇÃO INDUSTRIAL',
    'HM INSTALAÇÕES',
    'TEMP CLEAN',
    'SUEZ',
    'PWC',
    'FANUC',
    'OWENS',
    'ACEROLIMA',
    'AMBEV',
    'MELO ARQUITETURA',
    'TECFORGEL',
    'ISOLAR',
    'FOCO ENGENHARIA',
    'L.E. NORDESTE',
    'CCC STUDIO',
    'RESCOR',
    'MTX',
    'S. INTELIGENCIA',
    'LASA',
    'CRISTALPET',
    'CASTANHA FESTAS E EVENTOS',
    'HCJ',
    'PLUS MED',
    'Mettler Toledo',
    'NORSUPRI',
    'GRUPO RAVI',
    'ENGENHARI',
    'COATING ENGENHARIA',
    'NE LUBRIFICANTES',
    'FERRO NORTE',
    'USIMETAIS',
    'ACGUA',
    'KEOFITT',
    'VENEZA',
    'XMAK',
    'UNILEVER',
    'BBULL',
    'USINA SERRA GRANDE',
    'ESOERANÇA',
    'CHJ',
    '2AENGENHARIA',
    'AV. ENGENHARIA',
    'KLABIN',
    'TEADIT',
    'arquit',
    'ENGEL COMPANY',
    'PAPA MÍDIA',
    'OURO VERDE',
    'ASA COMUNICAÇÃO',
    'OM SERVICES',
    'APOIO AMBIENTAL',
    'RUSSO NORDESTE',
    'MAYKAEWER',
    'PRODEMIR',
    'MATEUS SUPER',
    'UNINASAL',
    'OLIVEIRA MONTAGENS',
    'SERVICES',
    'Mary Kay',
    'FACULDADE ESTACIO',
    'movex',
    'SRC',
    'HIDRUSCOM',
    'ACS ENG',
    'DENAN',
    'D&A Decoração',
    'ALFA TREINAMENTOS',
    'Rotulo savassa',
    'TWA',
    'KURITA',
    'DANTAS ENG',
    'SERVITEC ENGENHARIA',
    'F.ARAUJO',
    'BRITO Vieira',
    'ELETROMECANICA',
    'BERMO',
    'MENPLAM',
    'TIVIT',
    'REPIPE',
    'Georg Fscher',
    'INDUSERVICE',
    '44',
    'INSTALTEC TECNOLOGIA EM INSTALAÇÕES',
    'ELETROINOX',
    'MALHARIA MIRANTE',
    'VISÃO',
    'BRASIL TINTAS',
    'SEGTEC',
    'PREVEN SEGURANÇA',
    'PROTGE SMS',
    'MUCK',
    'CASCADURA',
    'infinit',
    'P  LOG',
    'SERVCAP',
    'FLATECK',
    'ENGEMELT',
    'ENDUT',
    'CEDROS',
    'LTDA',
    'PRFILGRAF',
    'PLASTIC SOLDA',
    'TRANS DEL',
    'MESA BRASIL',
    'TOYOTAO REBOQUE',
    'SERVICE PACK',
    'GENORMA',
    'CASA',
    'RPA   TRANSPORTES',
    'FENGSEG',
    'PINHEIRO',
    'ZEUS ELETRICA',
    'metrohm',
    'PV ENGENHARIA',
    'ESPIRAL',
    'DT TECNO. ELETRONICAS',
    'ELETROCENTER',
    'tecban',
    'ASUSU FILMAGENS',
    'ANTON PAR',
    'IAVECHAMAR',
    'ENGE',
    'VIRGILANCIA SANITARIA DA BAHIA',
    'MARINE',
    'LUMINAR',
    'FOCO MACHINE EXPRESS',
    'TELENSAT',
    'ECOFRIO',
    'mcfal',
    'TRAÇÃO',
    'CARVALHO CONSULTORIA',
    'center motos',
    'SHNEIDER ELECTRIC',
    'locah',
    'B& S - AUTOMAÇÃO',
    'Solution',
    'MONTANA',
    'MAYEKAWA',
    'JCTM',
    'ML Guindaste',
    'RCA',
    'FOCO',
    'DWA ENG',
    'NAC.Guinchos',
    'HIGHEND',
    'SERVICOM',
    'METALURGICA VALENTE',
    'Spraying System',
    'MA BEVERAGE',
    'DOURO ENGENHARIA',
    'HITA - COMERCIO E SERVIÇOS',
    'HIDROCON',
    'VPA AUTOMAÇÃO',
    'USINA TRAPICHE',
    'MOTIR - ON',
    'ALLSTEEL',
    'AERO ARQ',
    'SHIFT POWER',
    'eg muck',
    'KECHER',
    'DITRIBUIÇÃO',
    'PREDIMIX',
    'USICOM',
    'TREINAMENTOS',
    'REFRESCOS GUARARAPES LTDA',
    'NORSA REFRIGERANTES SA',
    'CAF - CRYSTAL AGUAS DO NORDESTE LTDA',
    'SOLAR BEBIDAS SA',
    'Policial',
    'SOLAR',
    'Cab',
    'R&M Tecnologia',
    'FANTASIA TESTE',
    'CPRH',
    'VIDEOJET',
    'MAXIMO SMS',
    'SAIF CLIMATIZAÇÃO SERVIÇOS E VENDAS DE PEÇAS',
    'AIRES',
    'TS GUINCHO',
    'NTN BRASIL',
    'NTN',
    'VIDEO SEGURANÇA',
    'IMPACTO SONORIZACOES',
    'SS CONSTRUÇÕES',
    'ISNADIA OLIVEIRA SOUSA',
    'WORKTEC',
    'SOARES LEAL',
    'THIGO OLIVEIRA DECOR.',
    'ECOL',
    'ALCAM INDUSTRIAL',
    'DL GUINCHO E CONTAINER',
    'valgroup',
    'ZEGLA',
    'COIOTE SEGURANÇA ELETRONICA',
    'LV EVENTOS',
    'DJ CARLOS  MASSA',
    'HIDROS COMERCIO LTDA',
    'INFRALINK',
    'TDI',
    'BOM FIM ENGENHARIA',
    'FIBRASA',
    'MCR',
    'PRORAD',
    'MANISA',
    'SIL',
    'CHNUT',
    'MIURA',
    'ECOMONTAGEM',
    'GRUPOFORT',
    'RENTOKIL',
    'WHITE MARTINS',
    'BRASANITAS',
    'GRUPO FORTE',
    'SAIF',
    'JURUA MOTOS',
    'MOTOBEL',
    'MOV LOG',
    'SILVANO E SILAVO',
    'HMPC',
    'MULTISERVICE',
    'EM DA SILVA SERVICOS ME',
    'ACCENTURE',
    'RECICLATE',
    'USINAFA',
    'AUTECMA',
    'B&F DIAS',
    'SOLAR BR',
    'TRACTIAN',
    'LOW CAST',
    'FERGAL',
    'Culture Filmes',
    'TUNAP',
    'LAX',
    'CYKLOP',
    'RS ROSENDO',
    'Construprev',
    'REUNAX - SERVICE',
    'Jose Robson Vieira da Silva',
    'Holanda Refrigeracao',
    'MIB ARMAZENS',
    'CLINERGY',
    'TPF',
    'ST-ONE',
    'GN TRANSPORTES',
    'METALUNOX',
    '3D CRIAR',
    'QUEO NETICS',
    'TECNOVAL',
    'NSK',
    'SF ENGENHARIA',
    'ROMELEVA',
    'PISANI',
    'SERCOS NORDESTES',
    'AMBIPAR',
    'INTERLUB',
    'OCS INSTALAÇÕES INDUSTRIAIS',
    'TELMEX',
    'INVICTA',
    'MYSNARSKI',
    'QUALITEX',
    'Bradesco PAB',
    'CENTRAL DE RESIDUOS',
    'ARSEG',
    'TRIXLOG',
    'sesi saude',
    'RS MANGUEIRAS',
    'ALESSANDRE ANDRADE ARQUITETURA ENGENHARIA',
    'ORGUEL',
    'JH ENGENHARIA',
    'O POSITIVO',
    'WORKSAFE',
    'JML',
    'AGISA',
    'HM INSTALAÇÕES INDUSTRAIS',
    'SILVANO E SILVANO',
    'ARAUJO ABREU ENGENHARIA NORTE',
    'BUILDMARK',
    'PARAGUAÇU ENGENHARIA',
    'BLOWER',
    'SICK',
    'CNPJ / CPF',
    'INFRAESTRUTURA',
    'NORTE VALVULAS',
    'HIDROSAM',
    'TEC GAS',
    'SAMSON',
    'MAGMA',
    'TDM',
    'CIDADE LIMPA',
    'PAPEL E CIA PRODUTOS DE PAPELARIAS LTDA',
    'SS EXPRESSO',
    'TSI',
    'Grupo Simoes',
    'RST',
    'ICONE',
    'MILENA PAIVA',
    'BIEL MOTOS',
    'FS LOG',
    'ASIAN COMPANY',
    'CALMAN',
    'ACM',
    'PHX',
    'ANA LUCIA',
    'COMERCIAL YOKOYAMA',
    'BRASCOLOR GRAFICA E EDITORA',
    'MONITORA',
    'XPA ENGENHARIA',
    'NACIONAL GAS',
    'MULTINORTE',
    'JAPA PRINT',
    'ENGEBANK',
    'BELNAVE',
    'AV FARIAS',
    'GNV',
    'TALENT',
    'NETPRIMUS',
    'ABRAZON',
    'MULTI ANALISES',
    'PIAUI SAFETY',
    'DISA',
    'GAS METAL',
    'ALFA METAL',
    'PARAMUCK',
    'COSTA E CARVALHO COMERCIO',
    'ATLAS COPCO',
    'SCHMERSAL',
    'ESTILO MANUTENCAO',
    'DISBRAVA',
    'FRUTEX',
    'ENJOY',
    'HEINEKEIN',
    'VGA',
    'CSC',
    'M&Y TRANSPORTE',
    'PARA FERRO',
    'SYNTHOIL',
    'MOTORGEL',
    'STELA',
    'MARFRIO',
    'ASA CONSTRUTORA',
    'CARBOMAN',
    'MENTEC',
    'RBT',
    'DURBETON',
    'LUX PLACAS',
    'LEMAR',
    'RESISTENCIA',
    'ACRILUX',
    'EAGLE ELETRICA',
    'EGUILHERME',
    'MAKO',
    'LEGALISA',
    'GOLD ENGENHARIA',
    'CENTURY',
    'RODOVITOR TRANSPORTES E LOC VEIC',
    'DENIS GROUP',
    'BRAGA CONSULTORA',
    'PLATINOX COMERCIO DE EQUIPAMENTOS',
    'ATUAL CARGA',
    'IMPERSIK',
    'GUERCIA CONSULTORIA',
    'GEDOR',
    'ROBOPAC',
    'UNIQUE',
    'MIRA',
    'VARANDA',
    'KINGSPAH',
    'AIRLIQUIDE',
    'TRATOMAR',
    'SERVPACK',
    'HIDRADYNE',
    'JUMP',
    'PAGUE MENOS',
    'MAIS GAS',
    'FLUSSO',
    'JD SERVIÇOS DE ENGENHARIA',
    'AUTO DEFESA BRASIL',
    'NLOG',
    'SCARF',
    'AZIMUTE',
    'SOVEDAÇÕES',
    'ESTILOS MANUTENÇÕES',
    'PERFET',
    'BERTOLINI',
    'COBERTURA E CIA',
    'FC',
    'BRADO',
    'CRETA',
    'AMP',
    'INOVA',
    'THAYRONECELL',
    'MEDSAFE',
    'ABZ SEGURANÇA',
    '2 DUO TRANSPORTE LTDA',
    'NASCIONAL GAS',
    'GR SA',
    'HALLER CONSULTORIA E RECURSOS HUMANOS LTDA',
    'QUIMICA CREDI',
    'LONGA ARMAZENAGEM',
    'trans paulistana',
    'LCC',
    'MB',
    'P MAS',
    'SR ENGENHARIA',
    'MENGONI',
    'ALUCEL',
    'INOX MARANHÃO',
    'Coplast Industria Química LTDA',
    'ENVIRONMENT BRASIL',
    'BEVAP',
    'PRONTO PLACA',
    'VALE AUTOMAÇÃO',
    'CONSTRUTORA EBERIK',
    'MECATRON',
    'MAKO ENGENHARIA',
    'MARCO ENGENHARIA',
    'R CONSULT',
    'RAÇA TRANSPORTE',
    'FERRALTEC',
    'BRASIL AUTO CENTER',
    'ENGESTEAM',
    'KAMPER',
    'BARUFALDI',
    'AMAZON ELETRICA',
    'IPHONE LENDEL CELL',
    'HELIOP',
    'ALO SERVICE',
    'E3FIX ENGENHARIA',
    'DRJ TRANSPORTES',
    'SIMIC',
    'GUNTNER',
    'TELEMATICA',
    'ISHIDA BRASIL',
    'BALL',
    'AUTOMATIZA',
    'ANALITICA',
    'COMANDO  METAL',
    'PREDICT',
    'CORPORATIVO',
    'CLARO S.A',
    'TORNEADORA AGAPE',
    'RESISTENCIA CONSULTORIA',
    'JF MULTI SERVIÇO',
    'GRS',
    'STM',
    'ESMATEC',
    'AGILETECH',
    'STAE ENGENHARIA LTDA',
    'cas',
    'INSTRUVAL',
    'TRANSOL',
    'ssma engenharia',
    'METRICA',
    'CASA DOS FILTROS',
    'BSP',
    'TECNOISO',
    'TRANSPAULISTANA',
    'HOMI AUTOMAÇÃO',
    'RENE MANUTENÇÃO',
    'TBA TRANSPORTES',
    'GE LOGISTICATK',
    'SCAN SOLO',
    'BELÉM TELHAS',
    'GEMO',
    'EXTINOVA',
    'LEMOS ENERGIA',
    'RAÇA',
    'LS PACK SERVICE',
    'CROWN',
    'TRANSDOURADA',
    'LJ MONTAGENS',
    'UNITECH',
    'PHOTO HAPPY',
    'RANGER SMS',
    'EB PROJETOS',
    'FORTE REAL',
    'A2 ENGENHARIA',
    'GEP',
    'GOVERNO DO ESTADO',
    'BENTOBRASIL',
    'VILI LOGISTICA',
    'policia',
    'ANHAGUERA',
    'SOLUCAPS',
    'QUEIROZ',
    'VCA CONSTRUTORA',
    'UNIRIOS',
    'GR Segurança',
    'Santys Produções',
    'ALTO PADRÃO  ENGENHARIA E TECNOLOGIA LTDA',
    'CRC',
    'INSTITUTO EMBELLEZE',
    'ASEMTE',
    'ROLAMENTOS CBF',
    'MANUTROL',
    'BATISTI TRANSPORTES',
    'SAPORIUM',
    'SODEXO',
    'FOX',
    'WB REFRIGERAÇÃO',
    'JP ENGENHARIA',
    'TEC ELETRICA',
    'Cruz Engearia',
    'TRANSCABRAL LTDA',
    'LEMOS PASSOS',
    'SERLARES',
    'SR EMBALAGENS',
    'CONECTE VOIP',
    'STA',
    'ENGEL ENGEARINHA',
    'IBC QUALIDADE',
    'MOAS',
    'MARP',
    'APTEC',
    'CAL SERVICE',
    'LISBOA',
    'ENGEPACK',
    'BEECORP',
    'KIS',
    'SENA & SANTOS',
    'ipersik',
    'LAGUA DOCE',
    'COMPAR RIO BRANCO',
    'SAP',
    'GLOBAL STANDARDES',
    'AST GUINDASTE',
    'EVIDENCIA LOGISTICA',
    'SEGUPRO',
    'SINI BAHIA',
    'construtora renova',
    'EQUATORIAL',
    'AMPI UNIFORMES',
    'NORTEC',
    'GUERCIA',
    '7 COM SERVICOS',
    'VIRGINIA MENDONÇA',
    'BALTECH',
    'DALLAS ARQUITETURA',
    'NOVO CICLO',
    'INTERGLESS',
    'ACS ENGENHARIA',
    'PILZ',
    'MONFAE',
    'LC ENGENHARIA',
    'INSTITUTO LIXO ZERO',
    'BR NORTE',
    'TRACTION',
    'A S SERVIÇOS',
    'COELHO VOIP',
    'EGS SERVICOS',
    'J CAMARGO ALTOMAÇÃO',
    'TOTAL SERVIÇO',
    'MAXSERV',
    'JUNGHEINRICH LIFT TRUCK',
    'MART PRINT',
    'ARAUJO OLIVEIRA',
    'IPIRANGA',
    'ZILQUIMICA',
    'COMPAR',
    'UNIÃO TRANSPORTES',
    'CONEC',
    'REBOKIT',
    'SARDO',
    'AB SERVIÇOS',
    'SYSTENS',
    'PRÁTICA',
    'DELTAMAQ',
    'H2Q',
    'VC2 RECURSOS HUMANOS',
    'RC TRANSPORTES',
    'WANS FARIAS',
    'COGTIVE',
    'ATIVA',
    'CARGO POLO',
    'AF TRABSPORTES',
    'UNIAO MULTIMODAL',
    'SALES ALMEIDA',
    'GE LOGISTICA',
    'VIA NORTE  LTDA',
    'PEREIRA LIMA',
    'RODOJUNIOR',
    'COMRANÇA',
    'COMFRANÇA',
    'EXPRESSO GERAÇÃO',
    'TGR',
    'TRANSWAC',
    'CTS TRANSPORTADORA',
    'PL',
    'USINA PETRIBU',
    'AGREGA MAIS',
    'RODOCELL TRANSPORTES E LOGISTICA',
    'EXPRESSO GERAÇÃO TRANPORTES',
    'FONTE D VIDA',
    'USINA ESTIVAS',
    'CONEXLOG',
    'HAPVIDA',
    'TREMEA',
    'SAFETECH IT',
    'ROSSO NORDESTE',
    'A M QUIMICA',
    'AZIMUTECH',
    'VITAL',
    'ULTRALOG',
    'ARMANI',
    'HYTEC',
    'CASA DOS ROLAMENTOS',
    'SUPER SONIC TRANSPORTES',
    'ROL PAF',
    'RAC',
    'META TRUCK',
    'EDIMETAL',
    'ANGELUS',
    'SAMPRED',
    'PREÇO BOM',
    'FACCHINI',
    'JERTMONT',
    'FINATTO',
    'SUSTENTARE',
    'ENSEI',
    'GABCO',
    'ENGEUS',
    'MEY TRANSPORTES',
    'RAVIBRAS',
    'RAPIDO FIGUEIREDO',
    'BSP TRANSPORTES',
    'AMAZONGAS',
    'YAMAMOTO',
    'PROTECNICA',
    'MAMUTH',
    'FERTÉCNICA',
    'DUNLOC',
    'DONALDSON',
    'QUINTAS COMUNICAÇÕES',
    'INVISTA',
    'CIGAS',
    'CYLTEST',
    'aledcor',
    'PARATY BEBIDAS',
    'INVITA',
    'FAST MONITORAMENTO E RASTREAMENTO VEICULAR',
    'ALTA PADRÃO ENG',
    'H S HAURADOU SISTEMAS',
    'Pp&C Auditores Independentes',
    'ADUKARGO',
    'ARKO SOLUCOES',
    'OMEGA NORTE',
    'DISMACON',
    'CAMPARI',
    'GELADOCE',
    'TEKNOFIK',
    'HILTI',
    'SETE COMERCIO E SERVICOS DE PNEUS LTDA',
    'ALE DECOR',
    'ALTO PADRAO ENGENHARIA',
    'METAL NOBRE',
    'COBAP',
    'ENTREGA ALMOXARIFADO',
    'A L C CAR SERVIÇOS',
    'HU',
    'MONACO MOTOCENTER',
    'NORTE MANUTENÇÃO',
    'NORTE SERVICE REFRIGERAÇÃO INDUSTRIAL LTDA',
    'RAÇA TRANS',
    'RR SERVIÇO',
    'CARDINALI BOMBAS',
    'SIL - MAGRI MANUTENCAO',
    'CONSTRUTORA E INCORPORADORA CORREIA & PEIXOTO LTDA',
    'BRADESCO  FVAG',
    'G R S A Serviços e Alimentacao LTDA',
    'HITSS DO BRASIL',
    'INTERATIVA EMPREENDIMENTOS',
    'Marina Queiroz',
    'Marina QPRTC',
    'TOPLINE',
    'CHICO TOUR TRANSPORTES EIRELI',
    'LIDERANCA LOGISTICA',
    'PORTO MOTOS',
    'PROGUARDA',
    'SAGA EQUIPAMENTOS E SIRVICOS EIRELI',
    'BANCO BRADESCO',
    'EM DA SILVA SERVICOS  ME',
    'SERVICE LOG',
    'NOVA SANTANA',
    'PROTEMAXI SEGURANÇA',
    'DIVERSEY BRASIL',
    'TRIX  log',
    'OSVALDO MIGUEL NEVES',
    'JARAQUI AUTOMATION LTDA',
    'CASTRO INDUSTRIAL',
    'TOKO TUBULACOES',
    'ISOLAR',
    'solar',
    'MONACO',
    'AUTONOMO',
    'solar arruda',
    'SERCOM EQUIPAMENTOS',
    'GRUPO LOUZA',
    'MANAUS DUTOS',
    'saimq',
    'MICRO-LAB',
    'SANTA ROSA',
    'AURORA LIVE MARKETING E EVENTOS LTDA',
    'M P DE SOUZA PONTES',
    'entrega',
    'MILLA TRANSPORTES',
    'OKAMOTO FLORES',
    'SEM EMPRESA',
    'construções amazonicas',
    'Teste de CNPJ',
    'cadastrando',
    'COLETA AUTOS',
    'PRECO BOM',
    'AMAZON CLEAN',
    'MZT CARGAS',
    '4 IRMAOS',
    'TRANSPORTE RODOVIARIO',
    'DWA ENGENHARIA',
    'El Condor',
    'HD LOGISTICA',
    'PALLETS BN',
    'segvieg',
    'CRISTAL ENGENHARIA',
    'sovel',
    'Robotersys',
    'KRONES DO BRASIL LTDA',
    'CROWN EMBALAGENS',
    'CONSTRUTORA ASA',
    'FC ENGENHARIA',
    'G&P ENGENHARIA',
    'POWER CLEAN',
    'a ELLOS SERVICOS AGENCIAMENTOS E TRANSPORTES DE CARGAS LTDA',
    'ellos refrigeração',
    'AMG Policlínica',
    'INTERATIVA',
    'SUZANO',
    '5001 TRANSPOTE',
    'PRESTEX ENCOMENDAS',
    'BALL BEVERAGE - ENTREGA',
    'SANITECK - POLISYSTEM SERVICO DE APOIO ADMINISTRATIVO LTDA',
    'MASTERFRIGO',
    'PL TRANSPORTES',
    'VALTECHE',
    'ZIEL ENGENHARIA',
    'GUIANOL',
    'SEST SENAT',
    'MIMAKI',
    'KALYKIM',
    'RECICLAGEM O NANDO',
    'NORTEMATIC',
    'NORTE MOTORES',
    'Majorseg',
    'RAMSONS',
    'PAULO VERAS SMS',
    'SUPERIOR TRANSPORTES LOCACAO E LOGISTICA LTDA',
    'LYON H ALVES ME',
    'Protemaxi Segurança Patrimonial Armada Eireli',
    'Interativa Empreendimentos e Servicos de Limpeza e Construcoes LTDA',
    'FACI WIDEM',
    'PANOSSI',
    'Interativa Empreendimentos e Servicos de Limpeza e Construcoes LTDA',
    'Technofrio Refrigeração',
    'SEMUSA',
    'MESQUITA ENGENHARIA',
    'ENGSHS',
    'K S NUNES',
    'DISA ECO',
    'JANSERV',
    'GRSEGURANCA',
    'RBT-CLIMAIZACAO',
    'RCR LOCACAO',
    'GR-ALIMENTACAO',
    'BRASALPLA BRASIL - INDUSTRIA DE EMBALAGENS LTDA',
    'UPTRON COMERCIO IMPORTACAO E EXPORTACAO LTDA',
    'PMAIS',
    'METRON PRODUÇÕES LTDA',
    'UNIR - UNIVERSIDADE FEDERAL DE RONDONIA',
    'Mancos Antonio',
    'Rafael Herreira',
    'Moisés',
    'COOPERCARGA',
    'PERNAMBUCO CONSTRUTORA',
    'GL ACABAMENTOS',
    'Christopher Pereira Teles',
    'UNAMA',
    'FORMATO TRANSPORTES',
    'ALUTEC',
    'DAYCA',
    'ZETALOC',
    'DINIZ TRANSPORTES',
    'SIRROS',
    'Solar Engenharia',
    'DESTAK',
    'SALVADOR',
    'MPM ALUGUEL DE AR',
    'AZZE',
    'VGE',
    'PROJEART',
    'JC TRANSPORTES',
    'MECESA',
    'RIFAS',
    'PASSARO TRANSPORTES',
    'T&R DE TAMONTI',
    'DMS MANUTENCAO',
    'SM MONTAGEM',
    'CDG SOLUTIONS',
    'SANITY FIRE',
    'SEBRAE',
    'EVR',
    'MUSSNICH',
    'GM TRANSPORTES',
    'PEDRO SOARES DE SOUZA MOBILIARIOS',
    'MD VIDRAÇARIA',
    'FUTURA',
    'JSL'
  ].sort();

  const unidades = ['ARD', 'BEL', 'BLM', 'CRR', 'DMU', 'FOR', 'JGS', 'JPA', 'MAO', 'MCZ', 'NAT', 'OCZ', 'PVH', 'RET', 'SLZ', 'SSA', 'SUA', 'THE', 'VAG', 'VDC'].sort();
  
  const grupos = ['R1', 'R2', 'R3'].sort();
  
  const setores = [
    'Comercial',
    'CSC',
    'DISTRIBUICAO',
    'EQS / GDM',
    'ESTOQUE / ALMOXARIFADO',
    'EXPEDICAO',
    'FROTA',
    'INFRAESTRUTURA',
    'LIMPEZA E JARDINAGEM',
    'LOGISTICA',
    'MAN. AUTOS',
    'MANUTENCAO INDUSTRIAL',
    'MANUTENCAO PREDIAL',
    'MARKETING',
    'MEIO AMBIENTE',
    'PORTARIA E SEG. PATRIMONIAL',
    'PRINT IN HOUSE',
    'PRODUCAO',
    'QUALIDADE',
    'RECICLAGEM',
    'REFEITORIO',
    'Residuos',
    'SEGURANCA DO TRABALHO'
  ].sort();

  const formatCPF = (value: string) => {
    const numbers = value.replace(/\D/g, '');
    if (numbers.length <= 11) {
      return numbers.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, '$1.$2.$3-$4');
    }
    return cpf;
  };

  const handleCPFChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const formatted = formatCPF(e.target.value);
    setCpf(formatted);
  };

  const handleCNPJChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    const formattedValue = value.replace(/\D/g, '').replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, '$1.$2.$3/$4-$5');
    setCnpj(formattedValue);
  };

  const validateForm = () => {
    if (!nomeCompleto.trim()) {
      toast({
        title: "Erro de validação",
        description: "Nome Completo deve ser preenchido.",
        variant: "destructive",
      });
      return false;
    }

    if (!cpf.trim() || cpf.replace(/\D/g, '').length !== 11) {
      toast({
        title: "Erro de validação",
        description: "CPF deve ser preenchido.",
        variant: "destructive",
      });
      return false;
    }

    if (!integracao) {
      toast({
        title: "Erro de validação",
        description: "Integração deve ser preenchido.",
        variant: "destructive",
      });
      return false;
    }

    if (!aso) {
      toast({
        title: "Erro de validação",
        description: "ASO deve ser preenchido.",
        variant: "destructive",
      });
      return false;
    }

    if (!pgroPcmat) {
      toast({
        title: "Erro de validação",
        description: "PGRO/PCMAT deve ser preenchido.",
        variant: "destructive",
      });
      return false;
    }

    if (!pcmso) {
      toast({
        title: "Erro de validação",
        description: "PCMSO deve ser preenchido.",
        variant: "destructive",
      });
      return false;
    }

    if (!empresa || !unidade || !grupo || !setor) {
      toast({
        title: "Erro de validação",
        description: "Empresa, Unidade, Grupo e Setor devem ser preenchidos.",
        variant: "destructive",
      });
      return false;
    }

    return true;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) return;

    const newCollaborator: Collaborator = {
      id: Date.now().toString(),
      nomeCompleto: nomeCompleto.trim(),
      cpf: cpf.trim(),
      empresa,
      cnpj: cnpj.trim(),
      novaEmpresa: novaEmpresa.trim(),
      unidade,
      grupo,
      setor,
      gestor: gestor.trim(),
      integracao,
      aso,
      nr10,
      nr10Sep,
      nr11,
      nr12,
      nr18,
      nr18Andaime,
      nr20,
      nr33,
      nr35,
      nr34,
      pgroPcmat,
      pcmso,
      ppr,
      loto,
      ptaPlataforma,
      treinamento,
      os,
      documentacao,
      aprPae,
      epi,
      cipa,
    };

    onAddCollaborator(newCollaborator);
    
    // Reset form - incluindo os novos checkboxes
    setNomeCompleto('');
    setCpf('');
    setEmpresa('');
    setCnpj('');
    setNovaEmpresa('');
    setUnidade('');
    setGrupo('');
    setSetor('');
    setGestor('');
    setIntegracao(null);
    setAso(null);
    setNr10(null);
    setNr10Sep(null);
    setNr11(null);
    setNr12(null);
    setNr18(null);
    setNr18Andaime(null);
    setNr20(null);
    setNr33(null);
    setNr35(null);
    setNr34(null);
    setPgroPcmat(null);
    setPcmso(null);
    setPpr(null);
    setLoto(null);
    setPtaPlataforma(null);
    setTreinamento(false);
    setOs(false);
    setDocumentacao(false);
    setAprPae(false);
    setEpi(false);
    setCipa(false);

    toast({
      title: "Colaborador adicionado",
      description: "Colaborador adicionado com sucesso!",
    });
  };

  const DatePicker = ({ 
    date, 
    onDateChange, 
    placeholder,
    required = false
  }: { 
    date: Date | null; 
    onDateChange: (date: Date | null) => void; 
    placeholder: string;
    required?: boolean;
  }) => (
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          className={cn(
            "w-full justify-start text-left font-normal",
            !date && "text-muted-foreground",
            required && !date && "border-red-500"
          )}
        >
          <CalendarIcon className="mr-2 h-4 w-4" />
          {date ? format(date, "dd/MM/yyyy") : <span>{placeholder}</span>}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0" align="start">
        <Calendar
          mode="single"
          selected={date || undefined}
          onSelect={onDateChange}
          initialFocus
          className="p-3 pointer-events-auto"
        />
      </PopoverContent>
    </Popover>
  );

  return (
    <Card className="w-full max-w-6xl mx-auto">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Plus className="h-5 w-5" />
          Adicionar Colaborador
        </CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Dados Pessoais */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">Dados Pessoais</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="nomeCompleto">Nome Completo *</Label>
                <Input
                  id="nomeCompleto"
                  type="text"
                  value={nomeCompleto}
                  onChange={(e) => setNomeCompleto(e.target.value)}
                  placeholder="Nome completo do colaborador"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="cpf">CPF *</Label>
                <Input
                  id="cpf"
                  type="text"
                  value={cpf}
                  onChange={handleCPFChange}
                  placeholder="000.000.000-00"
                  maxLength={14}
                  required
                />
              </div>
            </div>
          </div>

          {/* Dados Organizacionais */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">Dados Organizacionais</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="space-y-2">
                <Label>Empresa *</Label>
                <Select value={empresa} onValueChange={setEmpresa}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecionar empresa" />
                  </SelectTrigger>
                  <SelectContent>
                    {empresas.map((item) => (
                      <SelectItem key={item} value={item}>
                        {item}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="cnpj">CNPJ</Label>
                <Input
                  id="cnpj"
                  type="text"
                  value={cnpj}
                  onChange={handleCNPJChange}
                  placeholder="00.000.000/0000-00"
                  maxLength={18}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="novaEmpresa">Nova Empresa</Label>
                <Input
                  id="novaEmpresa"
                  type="text"
                  value={novaEmpresa}
                  onChange={(e) => setNovaEmpresa(e.target.value)}
                  placeholder="Nome da nova empresa"
                />
              </div>
              <div className="space-y-2">
                <Label>Unidade *</Label>
                <Select value={unidade} onValueChange={setUnidade}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecionar unidade" />
                  </SelectTrigger>
                  <SelectContent>
                    {unidades.map((item) => (
                      <SelectItem key={item} value={item}>
                        {item}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Grupo *</Label>
                <Select value={grupo} onValueChange={setGrupo}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecionar grupo" />
                  </SelectTrigger>
                  <SelectContent>
                    {grupos.map((item) => (
                      <SelectItem key={item} value={item}>
                        {item}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Setor *</Label>
                <Select value={setor} onValueChange={setSetor}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecionar setor" />
                  </SelectTrigger>
                  <SelectContent>
                    {setores.map((item) => (
                      <SelectItem key={item} value={item}>
                        {item}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="gestor">Gestor</Label>
                <Input
                  id="gestor"
                  type="text"
                  value={gestor}
                  onChange={(e) => setGestor(e.target.value)}
                  placeholder="Nome do gestor"
                />
              </div>
            </div>
          </div>

          {/* Datas de Vencimento */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">Datas de Vencimento</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="space-y-2">
                <Label>Integração *</Label>
                <DatePicker
                  date={integracao}
                  onDateChange={setIntegracao}
                  placeholder="Selecionar data"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>ASO *</Label>
                <DatePicker
                  date={aso}
                  onDateChange={setAso}
                  placeholder="Selecionar data"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>NR10</Label>
                <DatePicker
                  date={nr10}
                  onDateChange={setNr10}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR10-SEP</Label>
                <DatePicker
                  date={nr10Sep}
                  onDateChange={setNr10Sep}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR11</Label>
                <DatePicker
                  date={nr11}
                  onDateChange={setNr11}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR12</Label>
                <DatePicker
                  date={nr12}
                  onDateChange={setNr12}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR18</Label>
                <DatePicker
                  date={nr18}
                  onDateChange={setNr18}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR18 Andaime</Label>
                <DatePicker
                  date={nr18Andaime}
                  onDateChange={setNr18Andaime}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR20</Label>
                <DatePicker
                  date={nr20}
                  onDateChange={setNr20}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR33</Label>
                <DatePicker
                  date={nr33}
                  onDateChange={setNr33}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR35</Label>
                <DatePicker
                  date={nr35}
                  onDateChange={setNr35}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>NR34</Label>
                <DatePicker
                  date={nr34}
                  onDateChange={setNr34}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>PGRO/PCMAT *</Label>
                <DatePicker
                  date={pgroPcmat}
                  onDateChange={setPgroPcmat}
                  placeholder="Selecionar data"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>PCMSO *</Label>
                <DatePicker
                  date={pcmso}
                  onDateChange={setPcmso}
                  placeholder="Selecionar data"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>PPR</Label>
                <DatePicker
                  date={ppr}
                  onDateChange={setPpr}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>Loto</Label>
                <DatePicker
                  date={loto}
                  onDateChange={setLoto}
                  placeholder="Selecionar data"
                />
              </div>
              <div className="space-y-2">
                <Label>PTA Plataforma</Label>
                <DatePicker
                  date={ptaPlataforma}
                  onDateChange={setPtaPlataforma}
                  placeholder="Selecionar data"
                />
              </div>
            </div>
          </div>

          {/* Nova seção para os checkboxes */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">Documentação Adicional</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="treinamento"
                  checked={treinamento}
                  onCheckedChange={(checked) => setTreinamento(checked === true)}
                />
                <Label htmlFor="treinamento" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  Treinamento
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="os"
                  checked={os}
                  onCheckedChange={(checked) => setOs(checked === true)}
                />
                <Label htmlFor="os" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  OS
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="documentacao"
                  checked={documentacao}
                  onCheckedChange={(checked) => setDocumentacao(checked === true)}
                />
                <Label htmlFor="documentacao" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  Documentação
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="aprPae"
                  checked={aprPae}
                  onCheckedChange={(checked) => setAprPae(checked === true)}
                />
                <Label htmlFor="aprPae" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  APR/PAE
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="epi"
                  checked={epi}
                  onCheckedChange={(checked) => setEpi(checked === true)}
                />
                <Label htmlFor="epi" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  EPI
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="cipa"
                  checked={cipa}
                  onCheckedChange={(checked) => setCipa(checked === true)}
                />
                <Label htmlFor="cipa" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                  CIPA
                </Label>
              </div>
            </div>
          </div>

          <Button type="submit" className="w-full">
            <Plus className="mr-2 h-4 w-4" />
            Adicionar Colaborador
          </Button>
        </form>
      </CardContent>
    </Card>
  );
};

export default CollaboratorForm;
